# Generated by Django 4.2.9 on 2025-04-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Motivo de Perda',
                'verbose_name_plural': 'Motivos de Perda',
            },
        ),
    ]
