# Generated by Django 4.2.9 on 2025-04-29 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0002_lostreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostreason',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostreason',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
