# Generated by Django 4.2.9 on 2025-05-28 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0088_alter_historicalsale_status_alter_sale_status'),
        ('accounts', '0041_user_accounts_us_first_d_f43999_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0003_lostreason_created_at_lostreason_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tipo de Chamado')),
                ('deadline', models.PositiveIntegerField(help_text='Prazo em dias para resolução do chamado', verbose_name='Prazo (dias)')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Chamado',
                'verbose_name_plural': 'Tipos de Chamados',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Espera'), ('RE', 'Respondido'), ('R', 'Resolvido'), ('F', 'Fechado')], default='A', max_length=20, verbose_name='Status')),
                ('conclusion_date', models.DateField(blank=True, help_text='Data em que o chamado foi concluído', null=True, verbose_name='Data de Conclusão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.project', verbose_name='Projeto')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('responsible_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_department_tickets', to='accounts.department', verbose_name='Departamento Responsável')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_type_tickets', to='customer_service.tickettype', verbose_name='Tipo de Chamado')),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTicket',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Baixa'), (2, 'Média'), (3, 'Alta')], verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('A', 'Aberto'), ('E', 'Em Espera'), ('RE', 'Respondido'), ('R', 'Resolvido'), ('F', 'Fechado')], default='A', max_length=20, verbose_name='Status')),
                ('conclusion_date', models.DateField(blank=True, help_text='Data em que o chamado foi concluído', null=True, verbose_name='Data de Conclusão')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Atualizado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project', verbose_name='Projeto')),
                ('responsible', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('responsible_department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.department', verbose_name='Departamento Responsável')),
                ('responsible_user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
                ('ticket_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_service.tickettype', verbose_name='Tipo de Chamado')),
            ],
            options={
                'verbose_name': 'historical Chamado',
                'verbose_name_plural': 'historical Chamados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
