# Generated by Django 4.2.9 on 2025-05-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0004_tickettype_ticket_historicalticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='deadline',
            field=models.PositiveIntegerField(default=0, help_text='Prazo em dias para resolução do chamado', verbose_name='Prazo (dias)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.PositiveIntegerField(default=0, help_text='Prazo em dias para resolução do chamado', verbose_name='Prazo (dias)'),
            preserve_default=False,
        ),
    ]
