# Generated by Django 4.2.9 on 2025-05-28 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0088_alter_historicalsale_status_alter_sale_status'),
        ('customer_service', '0005_historicalticket_deadline_ticket_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tickets', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
