# Generated by Django 4.2.9 on 2025-06-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0006_alter_ticket_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, help_text='Data em que o chamado foi concluído', null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='conclusion_date',
            field=models.DateTimeField(blank=True, help_text='Data em que o chamado foi concluído', null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
