# Generated by Django 4.2.9 on 2025-06-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0007_alter_historicalticket_conclusion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='deadline',
            field=models.DurationField(help_text='Prazo em horas para resolução do chamado', verbose_name='Prazo (Em horas)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='deadline',
            field=models.DurationField(help_text='Prazo em horas para resolução do chamado', verbose_name='Prazo (Em horas)'),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='deadline',
            field=models.DurationField(help_text='Prazo em horas para resolução do chamado', verbose_name='Prazo (Horas)'),
        ),
    ]
