# Generated by Django 4.2.9 on 2025-06-03 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0008_alter_historicalticket_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o chamado foi respondido', null=True, verbose_name='Respondido em'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='answered_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o chamado foi fechado', null=True, verbose_name='Fechado em'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o chamado foi resolvido', null=True, verbose_name='Resolvido em'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='answered_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o chamado foi respondido', null=True, verbose_name='Respondido em'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Respondido por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o chamado foi fechado', null=True, verbose_name='Fechado em'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o chamado foi resolvido', null=True, verbose_name='Resolvido em'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Resolvido por'),
        ),
    ]
