# Generated by Django 4.2.9 on 2025-06-03 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0009_historicalticket_answered_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketsSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, unique=True, verbose_name='Assunto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Assunto de Chamado',
                'verbose_name_plural': 'Assuntos de Chamados',
                'ordering': ['subject'],
            },
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='observer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Observador'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='observer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Observador'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
