# Generated by Django 4.2.9 on 2025-06-03 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0010_ticketssubject_historicalticket_observer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalticket',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_service.ticketssubject', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_tickets', to='customer_service.ticketssubject', verbose_name='Assunto'),
        ),
    ]
