# Generated by Django 4.2.9 on 2025-06-10 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0010_ticketssubject_historicalticket_observer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketssubject',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ticketssubject',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalticket',
            name='subject',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_service.ticketssubject', verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_service.ticketssubject', verbose_name='Assunto'),
        ),
        migrations.CreateModel(
            name='HistoricalTicketsSubject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject', models.CharField(db_index=True, max_length=100, verbose_name='Assunto')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Assunto de Chamado',
                'verbose_name_plural': 'historical Assuntos de Chamados',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
