# Generated by Django 4.2.9 on 2025-06-11 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer_service', '0011_remove_ticketssubject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalticket',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='historicalticket',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Protocolo'),
        ),
    ]
