# Generated by Django 4.2.9 on 2025-06-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0012_historicalticket_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalticket',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='responsible_user',
        ),
    ]
