# Generated by Django 5.0.7 on 2024-09-02 12:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logistics/materials/')),
                ('description', models.CharField(max_length=80)),
                ('technical_description', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('measure_unit', models.CharField(max_length=8)),
                ('is_serialized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaterials',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(max_length=80)),
                ('technical_description', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('measure_unit', models.CharField(max_length=8)),
                ('is_serialized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Material',
                'verbose_name_plural': 'historical Materiais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
