# Generated by Django 5.0.7 on 2024-09-18 15:12

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_squad_boards'),
        ('inspections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Barras')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem')),
                ('description', models.CharField(max_length=80, verbose_name='Descrição')),
                ('technical_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição Técnica')),
                ('measure_unit', models.CharField(max_length=8, verbose_name='Unidade de Medida')),
                ('is_serialized', models.BooleanField(default=False, verbose_name='Serializado')),
                ('current_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo Atual')),
                ('current_type_category', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria do Tipo Atual')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
        migrations.CreateModel(
            name='MaterialTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Materiais',
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaterialTypes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Material',
                'verbose_name_plural': 'historical Tipos de Materiais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSolarEnergyKit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('inversor_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Inversores')),
                ('modules_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Módulos')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Preço')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Filial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('roof_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inspections.rooftype', verbose_name='Tipo de Telhado')),
                ('inversors_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Modelo dos Inversores')),
                ('modules_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Modelo dos Módulos')),
            ],
            options={
                'verbose_name': 'historical Kit de Materiais de Energia Solar',
                'verbose_name_plural': 'historical Kits de Materiais de Energia Solar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='materials',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.materialtypes', verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='HistoricalMaterials',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bar_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Barras')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem')),
                ('description', models.CharField(max_length=80, verbose_name='Descrição')),
                ('technical_description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição Técnica')),
                ('measure_unit', models.CharField(max_length=8, verbose_name='Unidade de Medida')),
                ('is_serialized', models.BooleanField(default=False, verbose_name='Serializado')),
                ('current_type', models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo Atual')),
                ('current_type_category', models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria do Tipo Atual')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materialtypes', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'historical Material',
                'verbose_name_plural': 'historical Materiais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Quantidade')),
                ('material_class', models.CharField(max_length=256, verbose_name='Classe do Material')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.materials', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Material da Venda',
                'verbose_name_plural': 'Materiais das Vendas',
            },
        ),
        migrations.CreateModel(
            name='SolarEnergyKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inversor_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Inversores')),
                ('modules_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Módulos')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Preço')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Filial')),
                ('inversors_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversors_kit_set', to='logistics.materials', verbose_name='Modelo dos Inversores')),
                ('modules_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_kit_set', to='logistics.materials', verbose_name='Modelo dos Módulos')),
                ('roof_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.rooftype', verbose_name='Tipo de Telhado')),
            ],
            options={
                'verbose_name': 'Kit de Materiais de Energia Solar',
                'verbose_name_plural': 'Kits de Materiais de Energia Solar',
            },
        ),
    ]
