# Generated by Django 5.0.7 on 2024-09-10 13:43

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Materiais',
            },
        ),
        migrations.AddField(
            model_name='historicalmaterials',
            name='bar_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código de Barras'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaterials',
            name='current_type',
            field=models.CharField(default='', max_length=8, verbose_name='Tipo Atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalmaterials',
            name='current_type_category',
            field=models.CharField(default='', max_length=20, verbose_name='Categoria do Tipo Atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='bar_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código de Barras'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='current_type',
            field=models.CharField(default='', max_length=8, verbose_name='Tipo Atual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materials',
            name='current_type_category',
            field=models.CharField(default='', max_length=20, verbose_name='Categoria do Tipo Atual'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='created_at',
            field=models.DateTimeField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='description',
            field=models.CharField(max_length=80, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='image',
            field=models.CharField(default='', max_length=100, verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='is_serialized',
            field=models.BooleanField(default=False, verbose_name='Serializado'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='measure_unit',
            field=models.CharField(max_length=8, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='technical_description',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição Técnica'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='created_at',
            field=models.DateTimeField(verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='description',
            field=models.CharField(max_length=80, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='image',
            field=models.CharField(default='', max_length=100, verbose_name='Imagem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='is_serialized',
            field=models.BooleanField(default=False, verbose_name='Serializado'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='measure_unit',
            field=models.CharField(max_length=8, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='technical_description',
            field=models.CharField(max_length=50, null=True, verbose_name='Descrição Técnica'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='HistoricalMaterialTypes',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Material',
                'verbose_name_plural': 'historical Tipos de Materiais',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SalesMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Quantidade')),
                ('material_class', models.CharField(max_length=256, verbose_name='Classe do Material')),
                ('created_at', models.DateTimeField(verbose_name='Criado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.materials', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Sales Material',
                'verbose_name_plural': 'Sales Materials',
            },
        ),
    ]
