# Generated by Django 5.0.7 on 2024-09-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
        ('resolve_crm', '0004_alter_sale_marketing_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Quantidade')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_set', to='logistics.materials', verbose_name='Material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_set', to='resolve_crm.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'Material do Projeto',
                'verbose_name_plural': 'Materiais dos Projetos',
            },
        ),
    ]
