# Generated by Django 5.0.7 on 2024-10-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_projectmaterials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material', 'verbose_name_plural': 'Materiais'},
        ),
        migrations.AlterModelOptions(
            name='materialtypes',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tipo de Material', 'verbose_name_plural': 'Tipos de Materiais'},
        ),
        migrations.AlterModelOptions(
            name='projectmaterials',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material do Projeto', 'verbose_name_plural': 'Materiais dos Projetos'},
        ),
        migrations.AlterModelOptions(
            name='salesmaterials',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material da Venda', 'verbose_name_plural': 'Materiais das Vendas'},
        ),
        migrations.AlterModelOptions(
            name='solarenergykit',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kit de Materiais de Energia Solar', 'verbose_name_plural': 'Kits de Materiais de Energia Solar'},
        ),
    ]
