# Generated by Django 5.0.7 on 2024-09-10 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_materialtypes_historicalmaterials_bar_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterials',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materialtypes', verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.materialtypes', verbose_name='Tipo'),
        ),
    ]
