# Generated by Django 5.0.7 on 2024-10-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_materials_options_alter_materialtypes_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Padrão'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Padrão'),
        ),
    ]
