# Generated by Django 5.0.7 on 2024-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_alter_historicalmaterials_type_alter_materials_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterials',
            name='bar_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='current_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo Atual'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='current_type_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria do Tipo Atual'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='technical_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição Técnica'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialtypes',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalmaterialtypes',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='bar_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='current_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Tipo Atual'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='current_type_category',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Categoria do Tipo Atual'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='technical_description',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Descrição Técnica'),
        ),
        migrations.AlterField(
            model_name='materialtypes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='materialtypes',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='salesmaterials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
