# Generated by Django 5.0.7 on 2024-09-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_historicalmaterials_bar_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesmaterials',
            options={'verbose_name': 'Material da Venda', 'verbose_name_plural': 'Materiais das Vendas'},
        ),
    ]
