# Generated by Django 5.0.9 on 2024-10-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_historicalsolarenergykit_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='kwp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='kWp'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='kwp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='kWp'),
        ),
    ]
