# Generated by Django 5.0.7 on 2024-09-12 18:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240911_1649'),
        ('inspections', '0001_initial'),
        ('logistics', '0005_alter_salesmaterials_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSolarEnergyKit',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('inversor_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Inversores')),
                ('modules_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Módulos')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Preço')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Filial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('inversors_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Modelo dos Inversores')),
                ('modules_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Modelo dos Módulos')),
                ('roof_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='inspections.rooftype', verbose_name='Tipo de Telhado')),
            ],
            options={
                'verbose_name': 'historical Kit de Materiais de Energia Solar',
                'verbose_name_plural': 'historical Kits de Materiais de Energia Solar',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SolarEnergyKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inversor_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Inversores')),
                ('modules_amount', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de Módulos')),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Filial')),
                ('inversors_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversors_kit_set', to='logistics.materials', verbose_name='Modelo dos Inversores')),
                ('modules_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules_kit_set', to='logistics.materials', verbose_name='Modelo dos Módulos')),
                ('roof_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.rooftype', verbose_name='Tipo de Telhado')),
            ],
            options={
                'verbose_name': 'Kit de Materiais de Energia Solar',
                'verbose_name_plural': 'Kits de Materiais de Energia Solar',
            },
        ),
    ]
