# Generated by Django 5.0.4 on 2024-11-08 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_historicaluser_branch_and_more'),
        ('field_services', '0001_initial'),
        ('logistics', '0005_historicalsolarenergykit_kwp_solarenergykit_kwp'),
        ('resolve_crm', '0018_alter_historicaltask_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='type',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='type',
        ),
        migrations.RemoveField(
            model_name='salesmaterials',
            name='material',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='bar_code',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='current_type',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='current_type_category',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='image',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='is_serialized',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalmaterials',
            name='technical_description',
        ),
        migrations.RemoveField(
            model_name='historicalsolarenergykit',
            name='inversor_amount',
        ),
        migrations.RemoveField(
            model_name='historicalsolarenergykit',
            name='inversors_model',
        ),
        migrations.RemoveField(
            model_name='historicalsolarenergykit',
            name='kwp',
        ),
        migrations.RemoveField(
            model_name='historicalsolarenergykit',
            name='modules_amount',
        ),
        migrations.RemoveField(
            model_name='historicalsolarenergykit',
            name='modules_model',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='bar_code',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='current_type',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='current_type_category',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='image',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='is_serialized',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='materials',
            name='technical_description',
        ),
        migrations.RemoveField(
            model_name='solarenergykit',
            name='inversor_amount',
        ),
        migrations.RemoveField(
            model_name='solarenergykit',
            name='inversors_model',
        ),
        migrations.RemoveField(
            model_name='solarenergykit',
            name='kwp',
        ),
        migrations.RemoveField(
            model_name='solarenergykit',
            name='modules_amount',
        ),
        migrations.RemoveField(
            model_name='solarenergykit',
            name='modules_model',
        ),
        migrations.AddField(
            model_name='historicalmaterials',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='cost_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Custo'),
        ),
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='product_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor do Produto'),
        ),
        migrations.AddField(
            model_name='historicalsolarenergykit',
            name='reference_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Referência'),
        ),
        migrations.AddField(
            model_name='materials',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='projectmaterials',
            name='is_exit',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Saída'),
        ),
        migrations.AddField(
            model_name='projectmaterials',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='cost_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Custo'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='description',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='product_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor do Produto'),
        ),
        migrations.AddField(
            model_name='solarenergykit',
            name='reference_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Referência'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='historicalsolarenergykit',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalsolarenergykit',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Padrão'),
        ),
        migrations.AlterField(
            model_name='historicalsolarenergykit',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='historicalsolarenergykit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects_set', to='logistics.materials', verbose_name='Material'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials_set', to='resolve_crm.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='solarenergykit',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Filial'),
        ),
        migrations.AlterField(
            model_name='solarenergykit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='solarenergykit',
            name='is_default',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Padrão'),
        ),
        migrations.AlterField(
            model_name='solarenergykit',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='solarenergykit',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='solarenergykit',
            name='roof_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_services.rooftype', verbose_name='Tipo de Telhado'),
        ),
        migrations.CreateModel(
            name='MaterialAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='logistics.materials', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Atributo do Material',
                'verbose_name_plural': 'Atributos dos Materiais',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Quantidade')),
                ('value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor do Produto')),
                ('reference_value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Referência')),
                ('cost_value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Custo')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('commercial_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='resolve_crm.comercialproposal', verbose_name='Proposta Comercial')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='resolve_crm.sale', verbose_name='Venda')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='logistics.solarenergykit', verbose_name='Kit de Energia Solar')),
            ],
            options={
                'verbose_name': 'Venda de Kit de Energia Solar',
                'verbose_name_plural': 'Vendas de Kits de Energia Solar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Quantidade')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='logistics.materials', verbose_name='Material')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='logistics.solarenergykit', verbose_name='Kit de Energia Solar')),
            ],
            options={
                'verbose_name': 'Material do Kit de Energia Solar',
                'verbose_name_plural': 'Materiais dos Kits de Energia Solar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='HistoricalMaterialTypes',
        ),
        migrations.DeleteModel(
            name='MaterialTypes',
        ),
        migrations.DeleteModel(
            name='SalesMaterials',
        ),
    ]
