# Generated by Django 5.0.4 on 2024-11-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_historicalmaterials_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialattributes',
            name='description',
        ),
        migrations.RemoveField(
            model_name='materialattributes',
            name='name',
        ),
        migrations.AddField(
            model_name='materialattributes',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave'),
        ),
        migrations.AddField(
            model_name='materialattributes',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valor'),
        ),
    ]
