# Generated by Django 5.0.4 on 2024-11-09 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_historicaluser_branch_and_more'),
        ('inspections', '0001_initial'),
        ('logistics', '0007_remove_materialattributes_description_and_more'),
        ('resolve_crm', '0024_alter_project_registered_circuit_breaker2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalSolarEnergyKit',
            new_name='HistoricalProduct',
        ),
        migrations.RenameModel(
            old_name='SolarEnergyKit',
            new_name='Product',
        ),
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Kit de Energia Solar', 'verbose_name_plural': 'historical Kits de Energia Solar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kit de Energia Solar', 'verbose_name_plural': 'Kits de Energia Solar'},
        ),
        migrations.AlterModelOptions(
            name='productmaterials',
            options={'ordering': ['-created_at'], 'verbose_name': 'Material do Produto', 'verbose_name_plural': 'Materiais dos Produtos'},
        ),
        migrations.AlterModelOptions(
            name='saleproduct',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produto da Venda', 'verbose_name_plural': 'Produtos das Vendas'},
        ),
    ]
