# Generated by Django 5.0.4 on 2024-11-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_rename_historicalsolarenergykit_historicalproduct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical product de Energia Solar', 'verbose_name_plural': 'historical products de Energia Solar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'product de Energia Solar', 'verbose_name_plural': 'products de Energia Solar'},
        ),
        migrations.AlterField(
            model_name='productmaterials',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='logistics.product', verbose_name='product de Energia Solar'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='logistics.product', verbose_name='product de Energia Solar'),
        ),
    ]
