# Generated by Django 5.0.4 on 2024-11-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_historicalproduct_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterials',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='materials',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=20, null=True, verbose_name='Preço'),
        ),
    ]
