# Generated by Django 5.0.4 on 2024-11-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_historicalmaterials_price_materials_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproduct',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Produto', 'verbose_name_plural': 'historical Produtos'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
