# Generated by Django 5.0.4 on 2024-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_historicalproduct_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
