# Generated by Django 5.0.4 on 2024-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_remove_historicalproduct_price_remove_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproduct',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='product_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Valor do Produto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Valor do Produto'),
        ),
    ]
