# Generated by Django 5.0.4 on 2024-11-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_historicalproduct_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterials',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalmaterials',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materials',
            name='price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, verbose_name='Preço'),
        ),
    ]
