# Generated by Django 5.0.4 on 2024-11-13 13:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0014_alter_historicalmaterials_name_and_more'),
        ('resolve_crm', '0029_historicallead_qualification_lead_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterials',
            name='amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='is_exit',
            field=models.BooleanField(default=False, verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='material',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.materials', verbose_name='Material'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmaterials',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.project', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
