# Generated by Django 5.0.4 on 2024-11-14 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_alter_projectmaterials_amount_and_more'),
        ('resolve_crm', '0033_remove_historicalsale_document_completion_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.comercialproposal', verbose_name='Proposta Comercial'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.sale', verbose_name='Venda'),
        ),
    ]
