# Generated by Django 5.0.4 on 2024-11-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_saleproduct_commercial_proposal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_default',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='default',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True, verbose_name='Padrão'),
        ),
        migrations.AddField(
            model_name='product',
            name='default',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, null=True, verbose_name='Padrão'),
        ),
    ]
