# Generated by Django 5.0.4 on 2024-11-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_remove_historicalproduct_is_default_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='logistics.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='reference_value',
            field=models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=20, null=True, verbose_name='Valor de Referência'),
        ),
    ]
