# Generated by Django 5.0.4 on 2024-11-25 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0018_alter_saleproduct_product_and_more'),
        ('resolve_crm', '0040_alter_historicalsale_transfer_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleproduct',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_products', to='resolve_crm.comercialproposal', verbose_name='Proposta Comercial'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_products', to='resolve_crm.sale', verbose_name='Venda'),
        ),
    ]
