# Generated by Django 5.0.4 on 2024-12-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0019_alter_saleproduct_commercial_proposal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmaterials',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
