# Generated by Django 5.0.4 on 2025-01-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_department_email_and_more'),
        ('logistics', '0020_alter_historicalmaterials_name_alter_materials_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproduct',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='product',
            name='branch',
        ),
        migrations.AddField(
            model_name='product',
            name='branch',
            field=models.ManyToManyField(blank=True, to='accounts.branch', verbose_name='Filial'),
        ),
    ]
