# Generated by Django 5.0.4 on 2025-01-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_department_email_and_more'),
        ('logistics', '0021_remove_historicalproduct_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ManyToManyField(to='accounts.branch', verbose_name='Filial'),
        ),
    ]
