# Generated by Django 5.0.4 on 2025-01-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0022_alter_product_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaterials',
            name='is_extra',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='materials',
            name='is_extra',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Extra'),
        ),
    ]
