# Generated by Django 5.0.4 on 2025-01-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0023_historicalmaterials_is_extra_materials_is_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduct',
            name='params',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Parâmetros'),
        ),
        migrations.AddField(
            model_name='product',
            name='params',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Parâmetros'),
        ),
    ]
