# Generated by Django 5.0.4 on 2025-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_employee_related_branches'),
        ('logistics', '0024_historicalproduct_params_product_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='branch',
            field=models.ManyToManyField(to='accounts.branch', verbose_name='Filiais'),
        ),
    ]
