# Generated by Django 5.0.4 on 2025-02-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0025_alter_product_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmaterials',
            name='material_class',
            field=models.CharField(blank=True, choices=[('K', 'Kit'), ('P', 'Padrão')], max_length=2, null=True, verbose_name='Classe do Material'),
        ),
    ]
