# Generated by Django 4.2.9 on 2025-03-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0026_projectmaterials_material_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(through='logistics.ProductMaterials', to='logistics.materials', verbose_name='Materiais'),
        ),
        migrations.AlterField(
            model_name='productmaterials',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='product de Energia Solar'),
        ),
    ]
