# Generated by Django 4.2.9 on 2025-04-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0027_product_materials_alter_productmaterials_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproduct',
            name='average_consumption',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Consumo Médio'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='estimated_consumption',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Consumo Estimado'),
        ),
    ]
