# Generated by Django 4.2.9 on 2025-04-17 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0028_saleproduct_average_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_material', to='logistics.product', verbose_name='product de Energia Solar'),
        ),
        migrations.CreateModel(
            name='HistoricalSaleProduct',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Quantidade')),
                ('value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor do Produto')),
                ('cost_value', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Valor de Custo')),
                ('reference_value', models.DecimalField(blank=True, decimal_places=6, default=1, max_digits=20, null=True, verbose_name='Valor de Referência')),
                ('average_consumption', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Consumo Médio')),
                ('estimated_consumption', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Consumo Estimado')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('commercial_proposal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.comercialproposal', verbose_name='Proposta Comercial')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.product', verbose_name='Produto')),
                ('sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'historical Produto da Venda',
                'verbose_name_plural': 'historical Produtos das Vendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProjectMaterials',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Quantidade')),
                ('material_class', models.CharField(blank=True, choices=[('K', 'Kit'), ('P', 'Padrão')], max_length=2, null=True, verbose_name='Classe do Material')),
                ('is_exit', models.BooleanField(default=False, verbose_name='Saída')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Material')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project', verbose_name='Projeto')),
            ],
            options={
                'verbose_name': 'historical Material do Projeto',
                'verbose_name_plural': 'historical Materiais dos Projetos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProductMaterials',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=20, null=True, verbose_name='Quantidade')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Material')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.product', verbose_name='product de Energia Solar')),
            ],
            options={
                'verbose_name': 'historical Material do Produto',
                'verbose_name_plural': 'historical Materiais dos Produtos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
