# Generated by Django 4.2.9 on 2025-05-03 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0029_alter_productmaterials_product_historicalsaleproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Entrega',
                'verbose_name_plural': 'Tipos de Entrega',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Entrega')),
                ('delivery_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.deliverytype', verbose_name='Tipo de Entrega')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Produto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.project', verbose_name='Projeto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
