# Generated by Django 4.2.9 on 2025-05-03 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
        ('logistics', '0030_deliverytype_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.CreateModel(
            name='HistoricalPurchase',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(blank=True, editable=False, verbose_name='Data do Pedido')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('delivery_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Entrega')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('delivery_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.deliverytype', verbose_name='Tipo de Entrega')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.product', verbose_name='Produto')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project', verbose_name='Projeto')),
                ('supplier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'historical Compra',
                'verbose_name_plural': 'historical Compras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeliveryType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('description', models.CharField(blank=True, max_length=80, null=True, verbose_name='Descrição')),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Entrega',
                'verbose_name_plural': 'historical Tipos de Entrega',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
