# Generated by Django 4.2.9 on 2025-05-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0031_purchase_created_at_purchase_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldeliverytype',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='delivery_type',
            field=models.CharField(choices=[('D', 'Entrega Direta'), ('C', 'Entrega CD')], default='P', max_length=1, verbose_name='Tipo de Entrega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='status',
            field=models.CharField(choices=[('R', 'Compra realizada'), ('C', 'Cancelada'), ('D', 'Distrato'), ('A', 'Aguardando pagamento'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_type',
            field=models.CharField(choices=[('D', 'Entrega Direta'), ('C', 'Entrega CD')], default='P', max_length=1, verbose_name='Tipo de Entrega'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('R', 'Compra realizada'), ('C', 'Cancelada'), ('D', 'Distrato'), ('A', 'Aguardando pagamento'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.DeleteModel(
            name='DeliveryType',
        ),
        migrations.DeleteModel(
            name='HistoricalDeliveryType',
        ),
    ]
