# Generated by Django 4.2.9 on 2025-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0032_remove_historicaldeliverytype_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpurchase',
            name='delivery_forecast',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='historicalpurchase',
            name='purchase_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Valor da Compra'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivery_forecast',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_value',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=20, verbose_name='Valor da Compra'),
        ),
        migrations.AlterField(
            model_name='historicalpurchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Data do Pedido'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(verbose_name='Data do Pedido'),
        ),
    ]
