# Generated by Django 4.2.9 on 2025-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0033_historicalpurchase_delivery_forecast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='status',
            field=models.CharField(choices=[('R', 'Compra realizada'), ('C', 'Cancelada'), ('D', 'Distrato'), ('A', 'Aguardando pagamento'), ('P', 'Pendente'), ('F', 'Aguardando Previsão de Entrega')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('R', 'Compra realizada'), ('C', 'Cancelada'), ('D', 'Distrato'), ('A', 'Aguardando pagamento'), ('P', 'Pendente'), ('F', 'Aguardando Previsão de Entrega')], default='P', max_length=1, verbose_name='Status'),
        ),
    ]
