# Generated by Django 4.2.9 on 2025-05-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0034_alter_historicalpurchase_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpurchase',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor da Compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Valor da Compra'),
        ),
    ]
