# Generated by Django 4.2.9 on 2025-05-07 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
        ('logistics', '0035_alter_historicalpurchase_purchase_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
