# Generated by Django 4.2.9 on 2025-05-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0036_alter_purchase_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpurchase',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='delivery_type',
        ),
    ]
