# Generated by Django 4.2.9 on 2025-05-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0037_remove_historicalpurchase_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['project', 'status'], name='logistics_p_project_162523_idx'),
        ),
    ]
