image: docker:20.10.7

services:
  - docker:20.10.7-dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /tmp/deploy_key.pem
  - chmod 600 /tmp/deploy_key.pem
  - cat /tmp/deploy_key.pem  
  - eval $(ssh-agent -s)
  - ssh-add /tmp/deploy_key.pem
  - mkdir -p ~/.ssh
  - ssh-keyscan -H $CI_SERVER >> ~/.ssh/known_hosts

build:
  stage: build
  script:
    - docker-compose -f docker-compose-prod.yml build
  only:
    - development

deploy:
  stage: deploy
  script:
    - scp -o StrictHostKeyChecking=no -i /tmp/deploy_key.pem docker-compose-prod.yml $CI_REGISTRY_USER@$CI_SERVER:/home/$CI_REGISTRY_USER/resolve_crm/
    - ssh -i /tmp/deploy_key.pem $CI_REGISTRY_USER@$CI_SERVER "cd /home/$CI_REGISTRY_USER/resolve_crm && git config --global credential.helper store && echo 'https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.com' > ~/.git-credentials && git pull origin development && sudo docker-compose -f docker-compose-prod.yml down && sudo docker-compose -f docker-compose-prod.yml up --build -d"
  only:
    - development
