# Generated by Django 5.0.7 on 2024-09-20 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_squad_boards_squad_task_templates'),
        ('core', '0001_initial'),
        ('resolve_crm', '0002_alter_historicallead_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='squad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='squad_boards', to='accounts.squad', verbose_name='Squad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='column',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='squad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.squad', verbose_name='Squad'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finalizado'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='resolve_crm.project'),
        ),
        migrations.AddField(
            model_name='tasktemplates',
            name='board',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='board_task_templates', to='core.board'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktemplates',
            name='column',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='column_tasks', to='core.column'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktemplates',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
