# Generated by Django 5.0.7 on 2024-09-20 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_board_squad_column_finished_historicalboard_squad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='task_template',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_template',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='column',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.column'),
        ),
        migrations.AddField(
            model_name='task',
            name='column',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='core.column'),
            preserve_default=False,
        ),
    ]
