# Generated by Django 5.0.7 on 2024-09-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_historicaltask_task_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='lead?'),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='lead?'),
        ),
    ]
