# Generated by Django 5.0.7 on 2024-09-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_board_statuses_remove_historicaltask_status_and_more'),
        ('resolve_crm', '0002_remove_historicallead_board_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardStatus',
        ),
        migrations.DeleteModel(
            name='HistoricalBoardStatus',
        ),
    ]
