# Generated by Django 5.0.7 on 2024-08-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalsquad_squad'),
        ('core', '0003_boardtemplate_board_branch_column_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='historicalboard',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
