# Generated by Django 5.0.7 on 2024-09-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_boardstatus_order_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardstatusesorder',
            unique_together={('board', 'status', 'order')},
        ),
    ]
