# Generated by Django 5.0.7 on 2024-08-20 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_board_branch_alter_board_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='is_completed_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
