# Generated by Django 5.0.7 on 2024-09-20 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_board_is_lead_historicalboard_is_lead'),
        ('resolve_crm', '0002_alter_historicallead_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='id_integration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de Integração'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='historicaltask',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='task',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='core.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='id_integration',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ID de Integração'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivado'),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Concluído'),
        ),
        migrations.AlterField(
            model_name='task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_owned', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
