# Generated by Django 5.0.7 on 2024-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicaltask_archived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='historicalboard',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
