# Generated by Django 5.0.7 on 2024-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_squad_task_templates'),
        ('core', '0005_remove_historicaltask_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalboard',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='board',
            name='squad',
        ),
        migrations.AddField(
            model_name='board',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='squad_boards', to='accounts.squad', verbose_name='Squad'),
        ),
    ]
