# Generated by Django 5.0.7 on 2024-09-20 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_historicalboard_squad_remove_board_squad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='squad',
        ),
    ]
