# Generated by Django 5.0.7 on 2024-10-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_board_squad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalwebhook',
            name='event',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], max_length=1),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='event',
            field=models.CharField(choices=[('C', 'Create'), ('U', 'Update'), ('D', 'Delete')], max_length=1),
        ),
    ]
