# Generated by Django 5.0.7 on 2024-10-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_historicalwebhook_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['title'], 'verbose_name': 'Quadro', 'verbose_name_plural': 'Quadros'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['position'], 'verbose_name': 'Coluna', 'verbose_name_plural': 'Colunas'},
        ),
        migrations.AlterModelOptions(
            name='historicalcolumn',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Coluna', 'verbose_name_plural': 'historical Colunas'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date'], 'verbose_name': 'Tarefa', 'verbose_name_plural': 'Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='tasktemplates',
            options={'ordering': ['title'], 'verbose_name': 'Modelo de Tarefa', 'verbose_name_plural': 'Modelos de Tarefas'},
        ),
        migrations.AlterModelOptions(
            name='webhook',
            options={'ordering': ['-created_at'], 'verbose_name': 'Webhook', 'verbose_name_plural': 'Webhooks'},
        ),
    ]
