# Generated by Django 5.0.7 on 2024-10-15 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_historicalwebhook_event_alter_webhook_event'),
        ('core', '0008_alter_historicalwebhook_event_and_more'),
    ]

    operations = [
    ]
