# Generated by Django 5.0.7 on 2024-10-30 17:31

from django.db import migrations

def create_permissions(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    permissions = [
        ('change_usermanager_field', 'Can change user manager field', 'accounts', 'User'),
        ('change_supervisor_field', 'Can change supervisor field', 'accounts', 'User'),
        ('change_seller_field', 'Can change seller field', 'accounts', 'User'),
        ('change_branch_field', 'Can change branch field', 'accounts', 'User'),
        ('view_all_own_department_paymentrequests', 'Can view all own department payment requests', 'financial', 'PaymentRequest'),
    ]
    
    for codename, name, app_label, model in permissions:
        content_type = ContentType.objects.get(app_label=app_label, model=model)
        Permission.objects.create(codename=codename, name=name, content_type=content_type)

def create_user_types(apps, schema_editor):
    UserType = apps.get_model('accounts', 'UserType')
    user_types = [
        (1, 'Fornecedor', None),
        (2, 'Cliente', None),
        (3, 'Funcionário', None),
    ]
    
    for id, name, description in user_types:
        UserType.objects.create(id=id, name=name, description=description)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_board_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_permissions),
        migrations.RunPython(create_user_types),
    ]
