# Generated by Django 5.0.4 on 2024-11-08 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_board_options_alter_column_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='board',
        ),
        migrations.RemoveField(
            model_name='historicaltask',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='board',
        ),
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='column',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='column',
            name='deadline',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='deadline',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='tasktemplates',
            name='automatico',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasktemplates',
            name='deadline',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
