# Generated by Django 5.0.4 on 2024-11-12 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20241015_1104'),
        ('core', '0010_remove_historicaltask_board_and_more'),
    ]

    operations = [
    ]
