# Generated by Django 5.0.4 on 2024-11-22 16:51

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0011_merge_20241112_1052'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('app_label', models.CharField(choices=[('accounts', 'Contas'), ('contracts', 'Contratos'), ('field_services', 'Inspeções'), ('logistics', 'Logística'), ('resolve_crm', 'CRM'), ('core', 'Core'), ('engineering', 'Engenharia'), ('financial', 'Financeiro')], max_length=100, verbose_name='App Label')),
                ('reusable', models.BooleanField(default=False, verbose_name='Reutilizável')),
                ('required', models.BooleanField(default=False, verbose_name='Obrigatório')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='core.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Subtipo de Documento',
                'verbose_name_plural': 'Subtipos de Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='resolve_crm/attachments/', verbose_name='Arquivo')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('document_subtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documentsubtype', verbose_name='Subtipo de Documento')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Anexo',
                'verbose_name_plural': 'Anexos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttachment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('object_id', models.PositiveSmallIntegerField()),
                ('file', models.TextField(max_length=100, verbose_name='Arquivo')),
                ('status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype')),
                ('document_subtype', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.documentsubtype', verbose_name='Subtipo de Documento')),
                ('document_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.documenttype', verbose_name='Tipo de Documento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Anexo',
                'verbose_name_plural': 'historical Anexos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
