# Generated by Django 5.0.4 on 2024-12-27 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_historicaltask_content_type_task_content_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktemplates',
            old_name='automatico',
            new_name='auto_create',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='task_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.tasktemplates', verbose_name='Modelo de Tarefa'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.tasktemplates', verbose_name='Modelo de Tarefa'),
        ),
    ]
