# Generated by Django 5.0.4 on 2025-01-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_automatico_tasktemplates_auto_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
