# Generated by Django 5.0.4 on 2025-01-01 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_historicaltask_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltask',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
    ]
