# Generated by Django 5.0.4 on 2025-01-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_tasktemplates_content_type_tasktemplates_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktemplates',
            name='object_id',
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasktemplates',
            name='component',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
