# Generated by Django 5.0.4 on 2025-01-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_tasktemplates_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplates',
            name='depends_on',
            field=models.ManyToManyField(blank=True, null=True, related_name='dependents', to='core.tasktemplates'),
        ),
        migrations.AlterField(
            model_name='tasktemplates',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
