# Generated by Django 5.0.4 on 2025-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_tasktemplates_depends_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.CharField(choices=[('B', 'Backlog'), ('T', 'To Do'), ('I', 'In Progress'), ('D', 'Done')], null=True, blank=True, max_length=1, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='column_type',
            field=models.CharField(choices=[('B', 'Backlog'), ('T', 'To Do'), ('I', 'In Progress'), ('D', 'Done')], null=True, blank=True, max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='tasktemplates',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='dependents', to='core.tasktemplates'),
        ),
    ]
