# Generated by Django 5.0.4 on 2025-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_column_column_type_historicalcolumn_column_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Posição'),
        ),
        migrations.AlterField(
            model_name='historicalcolumn',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Posição'),
        ),
    ]
