# Generated by Django 5.0.4 on 2025-01-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_column_position_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['board', 'name', 'position'], 'verbose_name': 'Coluna', 'verbose_name_plural': 'Colunas'},
        ),
        migrations.AlterField(
            model_name='column',
            name='column_type',
            field=models.CharField(blank=True, choices=[('B', 'Backlog'), ('T', 'To Do'), ('I', 'In Progress'), ('D', 'Done')], default='', max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='historicalcolumn',
            name='column_type',
            field=models.CharField(blank=True, choices=[('B', 'Backlog'), ('T', 'To Do'), ('I', 'In Progress'), ('D', 'Done')], default='', max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
