# Generated by Django 5.0.4 on 2025-01-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_column_options_alter_column_column_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='core.board', verbose_name='Quadro'),
        ),
    ]
