# Generated by Django 5.0.4 on 2025-01-25 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_column_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='column_type',
        ),
        migrations.RemoveField(
            model_name='historicalcolumn',
            name='column_type',
        ),
    ]
