# Generated by Django 5.0.4 on 2025-01-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_remove_column_column_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='column_type',
            field=models.CharField(blank=True, choices=[('B', 'Backlog'), ('T', 'To Do'), ('I', 'In Progress'), ('D', 'Done')], max_length=1, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='historicalcolumn',
            name='column_type',
            field=models.CharField(blank=True, choices=[('B', 'Backlog'), ('T', 'To Do'), ('I', 'In Progress'), ('D', 'Done')], max_length=1, null=True, verbose_name='Tipo'),
        ),
    ]
