# Generated by Django 5.0.4 on 2025-01-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_column_column_type_historicalcolumn_column_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_system_generated',
            field=models.BooleanField(default=False, verbose_name='Gerado pelo Sistema'),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='is_system_generated',
            field=models.BooleanField(default=False, verbose_name='Gerado pelo Sistema'),
        ),
    ]
