# Generated by Django 5.0.4 on 2025-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_systemconfig_historicalsystemconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsystemconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Configuração Sistêmica', 'verbose_name_plural': 'historical Configurações Sistêmicas'},
        ),
        migrations.AlterModelOptions(
            name='systemconfig',
            options={'verbose_name': 'Configuração Sistêmica', 'verbose_name_plural': 'Configurações Sistêmicas'},
        ),
    ]
