# Generated by Django 5.0.4 on 2025-02-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_comment_author_alter_comment_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggeditem',
            name='tag',
        ),
        migrations.AddField(
            model_name='taggeditem',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
