# Generated by Django 5.0.4 on 2025-02-25 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0033_remove_taggeditem_tag_taggeditem_name_delete_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='Tag')),
                ('color', models.CharField(max_length=7, verbose_name='Cor')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Item Taggeado',
                'verbose_name_plural': 'Itens Taggeados',
            },
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
