# Generated by Django 5.0.4 on 2025-02-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tag_delete_taggeditem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Taggeado', 'verbose_name_plural': 'Taggeados'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='object_id',
            field=models.PositiveSmallIntegerField(verbose_name='ID do Objeto'),
        ),
    ]
