# Generated by Django 5.0.4 on 2025-02-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_tag_options_alter_tag_object_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag'], 'verbose_name': 'Taggeado', 'verbose_name_plural': 'Taggeados'},
        ),
    ]
