# Generated by Django 4.2.9 on 2025-03-27 01:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_upload_to, verbose_name='Arquivo'),
        ),
    ]
