# Generated by Django 4.2.9 on 2025-03-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_attachment_file'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['document_type', 'status'], name='core_attach_documen_28932b_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='core_attach_content_d3cac2_idx'),
        ),
    ]
