# Generated by Django 4.2.9 on 2025-04-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_historicalprocessbase_historicalprocess_processbase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprocess',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='historicalprocessbase',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='process',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='processbase',
            name='tasks',
        ),
    ]
