# Generated by Django 4.2.9 on 2025-04-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_historicalprocess_tasks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Etapas'),
        ),
        migrations.AddField(
            model_name='historicalprocessbase',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Etapas'),
        ),
        migrations.AddField(
            model_name='process',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Etapas'),
        ),
        migrations.AddField(
            model_name='processbase',
            name='steps',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Etapas'),
        ),
    ]
