# Generated by Django 4.2.9 on 2025-04-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_historicalprocess_steps_historicalprocessbase_steps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprocess',
            name='current_step',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Etapa Atual'),
        ),
        migrations.AddField(
            model_name='process',
            name='current_step',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Etapa Atual'),
        ),
    ]
