# Generated by Django 4.2.9 on 2025-04-07 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0042_historicalprocess_current_step_process_current_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='historicalprocess',
            name='current_step',
        ),
        migrations.AlterField(
            model_name='historicalprocess',
            name='steps',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Etapas'),
        ),
        migrations.RemoveField(
            model_name='process',
            name='current_step',
        ),
        migrations.AlterField(
            model_name='process',
            name='steps',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Etapas'),
        ),
        migrations.CreateModel(
            name='HistoricalStepName',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Etapa',
                'verbose_name_plural': 'historical Etapas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='process',
            name='current_step',
            field=models.ManyToManyField(blank=True, related_name='current_step', to='core.stepname', verbose_name='Etapa Atual'),
        ),
    ]
