# Generated by Django 4.2.9 on 2025-04-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_stepname_remove_historicalprocess_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_customer_sendable',
            field=models.BooleanField(default=False, verbose_name='Enviável pelo Cliente?'),
        ),
    ]
