# Generated by Django 4.2.9 on 2025-04-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_documenttype_is_customer_sendable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStepCount',
            fields=[
                ('step', models.CharField(db_column='step', max_length=200, primary_key=True, serialize=False, verbose_name='Etapa')),
                ('total_processes', models.IntegerField(db_column='total_processes', verbose_name='Processos')),
            ],
            options={
                'db_table': 'vw_process_by_step',
                'managed': False,
            },
        ),
    ]
