# Generated by Django 4.2.9 on 2025-05-14 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_branch_marketing_tax_historicalbranch_marketing_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0046_contenttypeendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mentioned_departments',
            field=models.ManyToManyField(blank=True, related_name='mentioned_comments', to='accounts.department', verbose_name='Setores Mencionados'),
        ),
        migrations.AddField(
            model_name='comment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Mencionados'),
        ),
    ]
