# Generated by Django 5.0.7 on 2024-10-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='description',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Obrigatório'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='reusable',
            field=models.BooleanField(default=False, verbose_name='Reutilizável'),
        ),
        migrations.CreateModel(
            name='DocumentSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.documenttype', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Subtipo de Documento',
                'verbose_name_plural': 'Subtipos de Documentos',
                'ordering': ['name'],
            },
        ),
    ]
