# Generated by Django 5.0.4 on 2024-11-16 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='app_label',
            field=models.CharField(choices=[('accounts', 'Contas'), ('contracts', 'Contratos'), ('inspections', 'Inspeções'), ('logistics', 'Logística'), ('resolve_crm', 'CRM'), ('core', 'Core'), ('engineering', 'Engenharia'), ('financial', 'Financeiro')], default='accounts', max_length=100, verbose_name='App Label'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentsubtype',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='contracts.documenttype', verbose_name='Tipo de Documento'),
        ),
    ]
