# Generated by Django 5.0.4 on 2024-11-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_documenttype_app_label_and_more'),
        ('resolve_crm', '0038_remove_historicalattachment_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentSubType',
        ),
        migrations.DeleteModel(
            name='DocumentType',
        ),
    ]
