# Generated by Django 5.0.4 on 2025-03-13 17:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_delete_documentsubtype_delete_documenttype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSicoobRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100, verbose_name='Profissão')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda mensal')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado'), ('PA', 'Pré-Aprovado')], default='P', max_length=2)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('managing_partner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Sócio Administrador')),
            ],
            options={
                'verbose_name': 'historical Solicitação Sicoob',
                'verbose_name_plural': 'historical Solicitações Sicoob',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SicoobRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=100, verbose_name='Profissão')),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Renda mensal')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado'), ('PA', 'Pré-Aprovado')], default='P', max_length=2)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicoob_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('managing_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sicoob_requests_as_managing_partner', to=settings.AUTH_USER_MODEL, verbose_name='Sócio Administrador')),
            ],
            options={
                'verbose_name': 'Solicitação Sicoob',
                'verbose_name_plural': 'Solicitações Sicoob',
                'ordering': ['customer__complete_name'],
            },
        ),
    ]
