# Generated by Django 5.0.4 on 2025-03-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_historicalsicoobrequest_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsicoobrequest',
            name='project_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Projeto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sicoobrequest',
            name='project_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor do Projeto'),
            preserve_default=False,
        ),
    ]
