# Generated by Django 4.2.9 on 2025-05-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_branch_marketing_tax_historicalbranch_marketing_tax'),
        ('contracts', '0007_historicalsicoobrequest_project_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsicoobrequest',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='sicoobrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sicoob_requests', to='accounts.branch', verbose_name='Unidade'),
        ),
    ]
