# Generated by Django 4.2.9 on 2025-05-15 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_historicalsicoobrequest_branch_sicoobrequest_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sicoobrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação Sicoob', 'verbose_name_plural': 'Solicitações Sicoob'},
        ),
    ]
