# Generated by Django 5.0.7 on 2024-09-20 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolve_crm', '0002_alter_historicallead_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=14, verbose_name='Protocolo')),
                ('supplier', models.CharField(max_length=255, verbose_name='Fornecedor')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=6, max_digits=20, verbose_name='Valor')),
                ('service_date', models.DateField(verbose_name='Data de Serviço')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('causative_department', models.CharField(blank=True, max_length=8, null=True, verbose_name='Departamento Causador')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Forma de Pagamento')),
                ('id_bank_account', models.CharField(blank=True, max_length=8, null=True, verbose_name='Conta Bancária')),
                ('requesting_status', models.CharField(max_length=50, verbose_name='Status da Requisição')),
                ('manager_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Status do Gestor')),
                ('manager_status_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Status do Gestor')),
                ('financial_status', models.CharField(max_length=50, verbose_name='Status Financeiro')),
                ('financial_status_completion_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Status Financeiro')),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da Fatura')),
                ('id_omie', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Omie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_payments', to=settings.AUTH_USER_MODEL, verbose_name='Setor')),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.sale', verbose_name='Venda')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Gestor')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_payments', to=settings.AUTH_USER_MODEL, verbose_name='Requisitante')),
            ],
            options={
                'verbose_name': 'Requisição de Pagamento',
                'verbose_name_plural': 'Requisições de Pagamento',
                'ordering': ['-created_at'],
            },
        ),
    ]
