# Generated by Django 5.0.7 on 2024-10-24 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='installments_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financial.financier', verbose_name='Financiadora'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installments_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
    ]
