# Generated by Django 5.0.7 on 2024-09-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='category_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='category',
            field=models.CharField(max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='protocol',
            field=models.CharField(max_length=14, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='supplier',
            field=models.IntegerField(verbose_name='ID do Fornecedor no Omie'),
        ),
    ]
