# Generated by Django 5.0.7 on 2024-10-24 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_alter_historicalpayment_installments_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financial.payment', verbose_name='Pagamento'),
        ),
    ]
