# Generated by Django 5.0.7 on 2024-09-20 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_squad_squad_squad_boards'),
        ('financial', '0002_paymentrequest_category_name_and_more'),
        ('resolve_crm', '0003_alter_historicallead_type_alter_lead_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='causative_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='causative_department_payments', to='accounts.department', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_payments', to='accounts.department', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.sale', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da NF'),
        ),
    ]
