# Generated by Django 5.0.7 on 2024-09-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_paymentrequest_causative_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleResume',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('contract_number', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'db_table': 'saleid_customername_view',
                'ordering': ['contract_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDepartment',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('id_omie', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('teams_bot', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Departamento de Usuário',
                'verbose_name_plural': 'Departamentos de Usuários',
                'db_table': 'user_departments',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='paymentrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitação de Pagamento', 'verbose_name_plural': 'Solicitações de Pagamento'},
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='causative_department',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='supplier_name',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='action_date',
            field=models.CharField(blank=True, help_text='Data da ação relacionada à solicitação (se aplicável)', max_length=50, null=True, verbose_name='Data da Ação'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='id_causative_department',
            field=models.CharField(blank=True, help_text='Identificador do departamento que causou a solicitação (se aplicável)', max_length=8, null=True, verbose_name='ID do Departamento Causador'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='id_payment_detail',
            field=models.CharField(default='', help_text='Identificador do detalhe do pagamento', max_length=50, verbose_name='ID do Detalhe do Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='id_payment_request_supplier',
            field=models.CharField(default='', help_text='Identificador do fornecedor associado à solicitação de pagamento', max_length=256, verbose_name='ID do Fornecedor da Solicitação de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='id_user',
            field=models.CharField(default='', help_text='Identificador do usuário que realizou a solicitação', max_length=8, verbose_name='ID do Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='id_user_manager',
            field=models.CharField(default='', help_text='Identificador do gerente responsável', max_length=8, verbose_name='ID do Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização da solicitação', verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='amount',
            field=models.DecimalField(decimal_places=6, help_text='Valor total da solicitação de pagamento', max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='category',
            field=models.CharField(help_text='Categoria da solicitação de pagamento', max_length=50, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora em que a solicitação foi criada', verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='description',
            field=models.TextField(help_text='Descrição detalhada da solicitação de pagamento', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='due_date',
            field=models.DateField(help_text='Data de vencimento da solicitação de pagamento', verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='financial_status',
            field=models.CharField(help_text='Status financeiro da solicitação de pagamento', max_length=50, verbose_name='Status Financeiro'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='financial_status_completion_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o status financeiro foi concluído', null=True, verbose_name='Data de Conclusão do Status Financeiro'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id',
            field=models.CharField(help_text='Identificador único da solicitação de pagamento', max_length=8, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id_bank_account',
            field=models.CharField(blank=True, help_text='Identificador da conta bancária para o pagamento (se aplicável)', max_length=8, null=True, verbose_name='ID da Conta Bancária'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id_omie',
            field=models.CharField(blank=True, help_text='Identificador no sistema Omie (se aplicável)', max_length=50, null=True, verbose_name='ID Omie'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='id_sale',
            field=models.CharField(blank=True, help_text='Identificador da venda associada (se aplicável)', max_length=256, null=True, verbose_name='ID da Venda'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Número da fatura associada (se aplicável)', max_length=255, null=True, verbose_name='Número da Fatura'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='manager_status',
            field=models.CharField(blank=True, help_text='Status atualizado pelo gerente (se aplicável)', max_length=50, null=True, verbose_name='Status do Gerente'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='manager_status_completion_date',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que o gerente concluiu o status', null=True, verbose_name='Data de Conclusão do Status do Gerente'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='protocol',
            field=models.CharField(help_text='Protocolo da solicitação', max_length=14, verbose_name='Protocolo'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='requesting_status',
            field=models.CharField(help_text='Status atual da solicitação de pagamento', max_length=50, verbose_name='Status da Solicitação'),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='service_date',
            field=models.DateField(help_text='Data em que o serviço foi realizado', verbose_name='Data do Serviço'),
        ),
        migrations.AlterModelTable(
            name='paymentrequest',
            table='payment_requests',
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='id_user_department',
            field=models.ForeignKey(db_column='id_user_department', default='', help_text='Identificador do departamento do usuário', on_delete=django.db.models.deletion.CASCADE, to='financial.userdepartment', verbose_name='ID do Departamento do Usuário'),
            preserve_default=False,
        ),
    ]
