# Generated by Django 5.0.7 on 2024-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_alter_paymentinstallment_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='paymentinstallment',
            options={'ordering': ['-payment__created_at', 'installment_number'], 'verbose_name': 'Parcela', 'verbose_name_plural': 'Parcelas'},
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='installments_number',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='installments_number',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='is_paid',
        ),
    ]
