# Generated by Django 5.0.7 on 2024-10-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancier',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical financier', 'verbose_name_plural': 'historical financiers'},
        ),
    ]
