# Generated by Django 5.0.7 on 2024-10-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_financier_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='invoice_status',
            field=models.CharField(choices=[('E', 'Emitida'), ('L', 'Liberada'), ('P', 'Pendente'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Status da Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice_status',
            field=models.CharField(choices=[('E', 'Emitida'), ('L', 'Liberada'), ('P', 'Pendente'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Status da Nota Fiscal'),
        ),
    ]
