# Generated by Django 5.0.4 on 2024-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0006_historicalpayment_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financier',
            options={'ordering': ['name'], 'verbose_name': 'Financiadora', 'verbose_name_plural': 'Financiadoras'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancier',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Financiadora', 'verbose_name_plural': 'historical Financiadoras'},
        ),
    ]
