# Generated by Django 5.0.4 on 2024-11-22 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_historicalpayment_borrower_payment_borrower'),
        ('resolve_crm', '0038_remove_historicalattachment_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('PG', 'PAGO')], default='PE', max_length=2, verbose_name='Status')),
                ('repass_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='franchise_installments', to='resolve_crm.sale', verbose_name='Venda')),
            ],
        ),
    ]
