# Generated by Django 5.0.4 on 2024-11-22 18:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_franchiseinstallment'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinstallment',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Pago em'),
            preserve_default=False,
        ),
    ]
