# Generated by Django 5.0.4 on 2024-11-22 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_franchiseinstallment_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='franchiseinstallment',
            name='repass_percentage',
        ),
        migrations.AddField(
            model_name='franchiseinstallment',
            name='installment_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor da Parcela'),
        ),
    ]
