# Generated by Django 5.0.4 on 2024-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_remove_franchiseinstallment_repass_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseinstallment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pago em'),
        ),
    ]
