# Generated by Django 5.0.4 on 2024-11-25 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_alter_franchiseinstallment_paid_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='franchiseinstallment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parcela do Franquiado', 'verbose_name_plural': 'Parcelas do Franquiado'},
        ),
    ]
