# Generated by Django 5.0.4 on 2024-11-26 19:33

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_alter_franchiseinstallment_options'),
        ('resolve_crm', '0042_rename_document_completion_date_historicalproject_documention_completion_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFranchiseInstallment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'Pendente'), ('PG', 'PAGO')], default='PE', max_length=2, verbose_name='Status')),
                ('installment_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor da Parcela')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'historical Parcela do Franquiado',
                'verbose_name_plural': 'historical Parcelas do Franquiado',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
