# Generated by Django 5.0.4 on 2024-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_financialrecord_historicalfinancialrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseinstallment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('PG', 'Pago')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalfranchiseinstallment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('PG', 'Pago')], default='PE', max_length=2, verbose_name='Status'),
        ),
    ]
