# Generated by Django 5.0.4 on 2024-12-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_alter_franchiseinstallment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
    ]
