# Generated by Django 5.0.4 on 2025-01-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0018_alter_financier_address_alter_financier_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix'), ('T', 'Transferência Bancária')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix'), ('T', 'Transferência Bancária')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
    ]
