# Generated by Django 5.0.4 on 2025-01-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_alter_historicalpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='payment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
