# Generated by Django 5.0.4 on 2025-01-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_branch_energy_company_and_more'),
        ('financial', '0021_historicalpayment_observation_payment_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='requesting_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.department', verbose_name='Departamento Solicitante'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='requesting_department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.department', verbose_name='Departamento Solicitante'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Categoria'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='department_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Departamento'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='category_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código da Categoria'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='department_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Departamento'),
        ),
    ]
