# Generated by Django 5.0.4 on 2025-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_financialrecord_requesting_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitada'), ('E', 'Em Andamento'), ('P', 'Paga'), ('C', 'Cancelada')], default='S', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitada'), ('E', 'Em Andamento'), ('P', 'Paga'), ('C', 'Cancelada')], default='S', max_length=1, verbose_name='Status'),
        ),
    ]
