# Generated by Django 5.0.4 on 2025-01-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_alter_financialrecord_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialrecord',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='historicalfinancialrecord',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pago'), ('P', 'Pendente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='responsible_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas do Responsável'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='responsible_response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta do Gestor'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='responsible_status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status do Responsável'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pago'), ('P', 'Pendente'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='responsible_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas do Responsável'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='responsible_response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta do Gestor'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='responsible_status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status do Responsável'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
