# Generated by Django 5.0.4 on 2025-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_remove_financialrecord_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix'), ('T', 'Transferência Bancária'), ('DI', 'Dinheiro'), ('PA', 'Poste auxiliar'), ('RO', 'Repasse de Obra')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix'), ('T', 'Transferência Bancária'), ('DI', 'Dinheiro'), ('PA', 'Poste auxiliar'), ('RO', 'Repasse de Obra')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
    ]
