# Generated by Django 5.0.4 on 2025-02-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_alter_historicalpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_status',
            field=models.CharField(choices=[('PG', 'Pago'), ('P', 'Pendente'), ('C', 'Cancelado')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='payment_status',
            field=models.CharField(choices=[('PG', 'Pago'), ('P', 'Pendente'), ('C', 'Cancelado')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
    ]
