# Generated by Django 5.0.4 on 2025-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0026_alter_financialrecord_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='payment_method',
            field=models.CharField(choices=[('B', 'Boleto'), ('T', 'Transferência Bancária'), ('D', 'Dinheiro'), ('C', 'Cartão'), ('P', 'Pix')], default='P', max_length=1, verbose_name='Método de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='payment_method',
            field=models.CharField(choices=[('B', 'Boleto'), ('T', 'Transferência Bancária'), ('D', 'Dinheiro'), ('C', 'Cartão'), ('P', 'Pix')], default='P', max_length=1, verbose_name='Método de Pagamento'),
            preserve_default=False,
        ),
    ]
