# Generated by Django 5.0.4 on 2025-02-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0027_financialrecord_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_payable_financial_records', 'Can view all payable financial records'), ('view_all_department_payable_financial_records', 'Can view all payable financial_records from the department')], 'verbose_name': 'Conta a Pagar/Receber', 'verbose_name_plural': 'Contas a Pagar/Receber'},
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='category_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome da Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='client_supplier_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do Cliente/Fornecedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Departamento Causador'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='category_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome da Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='client_supplier_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome do Cliente/Fornecedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='department_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome do Departamento Causador'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='category_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código da Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='department_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Departamento Causador'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='category_code',
            field=models.CharField(default='', max_length=20, verbose_name='Código da Categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='department_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Departamento Causador'),
        ),
    ]
