# Generated by Django 5.0.4 on 2025-02-25 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_alter_financialrecord_options_and_more'),
        ('resolve_crm', '0071_lead_inspections'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='resolve_crm.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
