# Generated by Django 5.0.4 on 2025-02-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_financialrecord_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='project_integration_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código de Integração do Projeto'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='project_integration_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Código de Integração do Projeto'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='payment_method',
            field=models.CharField(choices=[('B', 'Boleto'), ('T', 'Transferência Bancária'), ('E', 'Dinheiro em Espécie'), ('D', 'Cartão de Débito'), ('C', 'Cartão de Crédito'), ('P', 'Pix')], max_length=1, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='payment_method',
            field=models.CharField(choices=[('B', 'Boleto'), ('T', 'Transferência Bancária'), ('E', 'Dinheiro em Espécie'), ('D', 'Cartão de Débito'), ('C', 'Cartão de Crédito'), ('P', 'Pix')], max_length=1, verbose_name='Método de Pagamento'),
        ),
    ]
