# Generated by Django 5.0.4 on 2025-03-06 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_branch_energy_company_and_more'),
        ('financial', '0030_financialrecord_project_integration_code_and_more'),
        ('resolve_crm', '0077_alter_comercialproposal_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_financial_records', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AlterField(
            model_name='financialrecord',
            name='responsible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responsible_financial_records', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='financier',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='franchiseinstallment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='franchise_installments', to='resolve_crm.sale', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Tomador'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='financier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.financier', verbose_name='Financiadora'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='resolve_crm.sale', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='financial.payment', verbose_name='Pagamento'),
        ),
    ]
