# Generated by Django 5.0.4 on 2025-03-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_alter_financialrecord_requester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinstallment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financial.payment', verbose_name='Pagamento'),
        ),
    ]
