# Generated by Django 5.0.4 on 2025-03-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0032_alter_paymentinstallment_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_payable_financial_records', 'Can view all payable financial records'), ('view_all_department_payable_financial_records', 'Can view all payable financial_records from the department'), ('view_financialrecord_attachment', 'Can view financial record attachment')], 'verbose_name': 'Conta a Pagar/Receber', 'verbose_name_plural': 'Contas a Pagar/Receber'},
        ),
    ]
