# Generated by Django 4.2.9 on 2025-04-10 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('financial', '0033_alter_financialrecord_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTypeEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('label', models.CharField(max_length=255, verbose_name='Rótulo')),
                ('queryParam', models.CharField(max_length=255, verbose_name='Parâmetro de Busca')),
                ('extraParams', models.CharField(blank=True, max_length=255, null=True, verbose_name='Parâmetros Extras')),
                ('content_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='contenttypes.contenttype', verbose_name='Tipo de Conteúdo')),
            ],
            options={
                'verbose_name': 'Endpoint do Tipo de Conteúdo',
                'verbose_name_plural': 'Endpoints dos Tipos de Conteúdo',
                'ordering': ['-endpoint'],
            },
        ),
    ]
