# Generated by Django 4.2.9 on 2025-04-10 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0034_contenttypeendpoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentTypeEndpoint',
        ),
    ]
