# Generated by Django 4.2.9 on 2025-04-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0035_delete_contenttypeendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='responsible_request_integration_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Integração da Solicitação ao Gestor'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='responsible_request_integration_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código de Integração da Solicitação ao Gestor'),
        ),
    ]
