# Generated by Django 4.2.9 on 2025-04-22 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0036_financialrecord_responsible_request_integration_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_supplier_code', models.BigIntegerField(verbose_name='Código do Cliente/Fornecedor')),
                ('financial_instituition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição Financeira')),
                ('agency_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Agência')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Conta')),
                ('account_type', models.CharField(choices=[('C', 'Corrente'), ('P', 'Poupança'), ('X', 'PIX')], max_length=1, verbose_name='Tipo de Conta')),
                ('pix_key_type', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Celular/Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=10, null=True, verbose_name='Tipo de Chave PIX')),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
            ],
            options={
                'verbose_name': 'Dados Bancários',
                'verbose_name_plural': 'Dados Bancários',
                'ordering': ['financial_instituition'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalBankDetails',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('client_supplier_code', models.BigIntegerField(verbose_name='Código do Cliente/Fornecedor')),
                ('financial_instituition', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instituição Financeira')),
                ('agency_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Agência')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da Conta')),
                ('account_type', models.CharField(choices=[('C', 'Corrente'), ('P', 'Poupança'), ('X', 'PIX')], max_length=1, verbose_name='Tipo de Conta')),
                ('pix_key_type', models.CharField(blank=True, choices=[('CPF', 'CPF'), ('CNPJ', 'CNPJ'), ('EMAIL', 'E-mail'), ('PHONE', 'Celular/Telefone'), ('RANDOM', 'Chave Aleatória')], max_length=10, null=True, verbose_name='Tipo de Chave PIX')),
                ('pix_key', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Dados Bancários',
                'verbose_name_plural': 'historical Dados Bancários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
