# Generated by Django 4.2.9 on 2025-04-22 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0037_bankdetails_historicalbankdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financial.bankdetails', verbose_name='Dados Bancários'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='bank_details',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='financial.bankdetails', verbose_name='Dados Bancários'),
        ),
    ]
