# Generated by Django 4.2.9 on 2025-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_financialrecord_bank_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinstallment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='historicalfranchiseinstallment',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
