# Generated by Django 4.2.9 on 2025-04-29 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_lostreason_created_at_lostreason_is_deleted'),
        ('financial', '0039_franchiseinstallment_observation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='lost_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer_service.lostreason', verbose_name='Motivo de Perda'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='lost_reason',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='customer_service.lostreason', verbose_name='Motivo de Perda'),
        ),
    ]
