# Generated by Django 4.2.9 on 2025-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0040_financialrecord_lost_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinstallment',
            name='marketing_tax',
            field=models.DecimalField(decimal_places=6, default=1.5, max_digits=20, verbose_name='Taxa de Marketing'),
        ),
        migrations.AddField(
            model_name='historicalfranchiseinstallment',
            name='marketing_tax',
            field=models.DecimalField(decimal_places=6, default=1.5, max_digits=20, verbose_name='Taxa de Marketing'),
        ),
    ]
