# Generated by Django 4.2.9 on 2025-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0041_franchiseinstallment_marketing_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchiseinstallment',
            name='margin',
            field=models.DecimalField(decimal_places=6, default=20.0, max_digits=20, verbose_name='Margem'),
        ),
        migrations.AddField(
            model_name='historicalfranchiseinstallment',
            name='margin',
            field=models.DecimalField(decimal_places=6, default=20.0, max_digits=20, verbose_name='Margem'),
        ),
    ]
