# Generated by Django 4.2.9 on 2025-05-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_franchiseinstallment_margin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseinstallment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('PG', 'Pago'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalfranchiseinstallment',
            name='status',
            field=models.CharField(choices=[('PE', 'Pendente'), ('PG', 'Pago'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Status'),
        ),
    ]
