# Generated by Django 4.2.9 on 2025-05-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0043_alter_franchiseinstallment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpayment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix'), ('T', 'Transferência Bancária'), ('DI', 'Dinheiro'), ('PA', 'Poste auxiliar'), ('RO', 'Repasse de Obra'), ('ND', 'Nota de Débito')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno'), ('P', 'Pix'), ('T', 'Transferência Bancária'), ('DI', 'Dinheiro'), ('PA', 'Poste auxiliar'), ('RO', 'Repasse de Obra'), ('ND', 'Nota de Débito')], max_length=2, verbose_name='Tipo de Pagamento'),
        ),
    ]
