# Generated by Django 4.2.9 on 2025-05-14 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0086_alter_project_options'),
        ('financial', '0044_alter_historicalpayment_payment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='franchiseinstallment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='franchise_installments', to='resolve_crm.sale', verbose_name='Venda'),
        ),
    ]
