# Generated by Django 4.2.9 on 2025-05-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0045_alter_franchiseinstallment_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='executor_work',
            field=models.CharField(blank=True, choices=[('C', 'Cliente'), ('F', 'Franquia'), ('CO', 'Centro de Operações')], max_length=200, null=True, verbose_name='Executor da Obra'),
        ),
        migrations.AddField(
            model_name='payment',
            name='executor_work',
            field=models.CharField(blank=True, choices=[('C', 'Cliente'), ('F', 'Franquia'), ('CO', 'Centro de Operações')], max_length=200, null=True, verbose_name='Executor da Obra'),
        ),
    ]
