# Generated by Django 4.2.9 on 2025-05-19 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0046_historicalpayment_executor_work_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_payments_after_issued', 'Can change payments after issued')], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
    ]
