# Generated by Django 4.2.9 on 2025-09-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0047_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('AA', 'Aguardando Aprovação'), ('EA', 'Em Análise'), ('C', 'Cancelado')], default='P', max_length=2, verbose_name='Status do Audit'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('AA', 'Aguardando Aprovação'), ('EA', 'Em Análise'), ('C', 'Cancelado')], default='P', max_length=2, verbose_name='Status do Audit'),
        ),
    ]
