# Generated by Django 4.2.9 on 2025-09-18 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('financial', '0048_financialrecord_audit_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialrecord',
            name='audit_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audited_financial_records', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='audit_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas do Audit'),
        ),
        migrations.AddField(
            model_name='financialrecord',
            name='audit_response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta do Audit'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='audit_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='audit_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notas do Audit'),
        ),
        migrations.AddField(
            model_name='historicalfinancialrecord',
            name='audit_response_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Resposta do Audit'),
        ),
    ]
