# Generated by Django 4.2.9 on 2025-09-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0049_financialrecord_audit_by_financialrecord_audit_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('AA', 'Aguardando Aprovação'), ('EA', 'Em Análise'), ('C', 'Cancelado')], default='AA', max_length=2, verbose_name='Status do Audit'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Aprovado'), ('R', 'Reprovado'), ('AA', 'Aguardando Aprovação'), ('EA', 'Em Análise'), ('C', 'Cancelado')], default='AA', max_length=2, verbose_name='Status do Audit'),
        ),
    ]
