# Generated by Django 4.2.9 on 2025-09-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0050_alter_financialrecord_audit_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialrecord',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_payable_financial_records', 'Can view all payable financial records'), ('view_all_department_payable_financial_records', 'Can view all payable financial_records from the department'), ('view_financialrecord_attachment', 'Can view financial record attachment'), ('can_change_audit_status', 'Can change audit status')], 'verbose_name': 'Conta a Pagar/Receber', 'verbose_name_plural': 'Contas a Pagar/Receber'},
        ),
    ]
