# Generated by Django 4.2.9 on 2025-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0051_alter_financialrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialrecord',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Aprovada'), ('R', 'Reprovada'), ('AA', 'Aguardando Aprovação'), ('EA', 'Em Análise'), ('C', 'Cancelada')], default='AA', max_length=2, verbose_name='Status do Audit'),
        ),
        migrations.AlterField(
            model_name='historicalfinancialrecord',
            name='audit_status',
            field=models.CharField(choices=[('A', 'Aprovada'), ('R', 'Reprovada'), ('AA', 'Aguardando Aprovação'), ('EA', 'Em Análise'), ('C', 'Cancelada')], default='AA', max_length=2, verbose_name='Status do Audit'),
        ),
    ]
