# Generated by Django 5.0.7 on 2024-09-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuitbreaker',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='historicalcircuitbreaker',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
