# Generated by Django 5.0.7 on 2024-09-19 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
        ('resolve_crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.project', verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
