# Generated by Django 5.0.7 on 2024-09-13 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240911_1649'),
        ('engineering', '0002_circuitbreaker_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EnergyDealership',
            new_name='EnergyCompany',
        ),
        migrations.RenameModel(
            old_name='HistoricalEnergyDealership',
            new_name='HistoricalEnergyCompany',
        ),
        migrations.RenameModel(
            old_name='HistoricalRequestsEnergyDealership',
            new_name='HistoricalRequestsEnergyCompany',
        ),
        migrations.RenameModel(
            old_name='RequestsEnergyDealership',
            new_name='RequestsEnergyCompany',
        ),
    ]
