# Generated by Django 5.0.7 on 2024-09-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_historicalunits_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunits',
            name='bill_file',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Arquivo da Fatura'),
        ),
        migrations.AddField(
            model_name='units',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to='units-biils/', verbose_name='Arquivo da Fatura'),
        ),
    ]
