# Generated by Django 5.0.7 on 2024-09-14 13:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240911_1649'),
        ('engineering', '0003_rename_energydealership_energycompany_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestsenergycompany',
            name='limit_date',
        ),
        migrations.RemoveField(
            model_name='requestsenergycompany',
            name='limit_date',
        ),
        migrations.AddField(
            model_name='energycompany',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='historicalenergycompany',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Conclusão'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='conclusion_registred',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Registro da Conclusão'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 13, 35, 6, 140126, tzinfo=datetime.timezone.utc), verbose_name='Data da Solicitação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='conclusion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Conclusão'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='conclusion_registred',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Registro da Conclusão'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='request_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 14, 13, 35, 19, 443335, tzinfo=datetime.timezone.utc), verbose_name='Data da Solicitação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='energycompany',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='energycompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='energycompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicalenergycompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='historicalenergycompany',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='historicalrequestsenergycompany',
            name='status',
            field=models.CharField(choices=[('P', 'Em andamento'), ('A', 'Deferido'), ('R', 'Indeferido')], max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='status',
            field=models.CharField(choices=[('P', 'Em andamento'), ('A', 'Deferido'), ('R', 'Indeferido')], max_length=2, verbose_name='Status'),
        ),
    ]
