# Generated by Django 5.0.7 on 2024-09-21 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_historicalunits_bill_file_units_bill_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunits',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conta contrato'),
        ),
        migrations.AlterField(
            model_name='units',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='units',
            name='unit_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Conta contrato'),
        ),
    ]
