# Generated by Django 5.0.7 on 2024-09-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_remove_historicalrequestsenergycompany_limit_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrequestsenergycompany',
            old_name='dealership',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='requestsenergycompany',
            old_name='dealership',
            new_name='company',
        ),
    ]
