# Generated by Django 5.0.7 on 2024-09-23 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_squad_squad_squad_boards'),
        ('engineering', '0005_alter_historicalunits_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunits',
            name='change_owner',
            field=models.BooleanField(default=False, verbose_name='Troca de Titularidade'),
        ),
        migrations.AddField(
            model_name='units',
            name='change_owner',
            field=models.BooleanField(default=False, verbose_name='Troca de Titularidade'),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='units',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Endereço'),
        ),
    ]
