# Generated by Django 5.0.7 on 2024-09-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0006_historicalunits_change_owner_units_change_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunits',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do medidor'),
        ),
        migrations.AlterField(
            model_name='units',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do medidor'),
        ),
    ]
