# Generated by Django 5.0.7 on 2024-09-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0006_historicalrequestsenergycompany_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestsenergycompany',
            name='status',
            field=models.CharField(choices=[('EA', 'Em andamento'), ('D', 'Deferido'), ('I', 'Indeferido')], max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='status',
            field=models.CharField(choices=[('EA', 'Em andamento'), ('D', 'Deferido'), ('I', 'Indeferido')], max_length=2, verbose_name='Status'),
        ),
    ]
