# Generated by Django 5.0.4 on 2024-11-08 18:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0007_alter_historicalunits_account_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResquestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Tipo de Solicitação',
                'verbose_name_plural': 'Tipos de Solicitação',
            },
        ),
        migrations.CreateModel(
            name='SituationEnergyCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Situação da Concessionária de Energia',
                'verbose_name_plural': 'Situações da Concessionária de Energia',
            },
        ),
        migrations.CreateModel(
            name='SupplyAdequance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Adequação de Fornecimento',
                'verbose_name_plural': 'Adequações de Fornecimento',
            },
        ),
        migrations.RemoveField(
            model_name='circuitbreaker',
            name='material',
        ),
        migrations.RemoveField(
            model_name='circuitbreaker',
            name='pole',
        ),
        migrations.RemoveField(
            model_name='historicalcircuitbreaker',
            name='material',
        ),
        migrations.RemoveField(
            model_name='historicalcircuitbreaker',
            name='pole',
        ),
        migrations.RemoveField(
            model_name='historicalrequestsenergycompany',
            name='conclusion_registred',
        ),
        migrations.RemoveField(
            model_name='historicalrequestsenergycompany',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='historicalunits',
            name='change_owner',
        ),
        migrations.RemoveField(
            model_name='requestsenergycompany',
            name='conclusion_registred',
        ),
        migrations.RemoveField(
            model_name='requestsenergycompany',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='units',
            name='change_owner',
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='name',
            field=models.CharField(default='teste ', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='circuitbreaker',
            name='tension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tensão'),
        ),
        migrations.AddField(
            model_name='historicalcircuitbreaker',
            name='name',
            field=models.CharField(default='teste', max_length=200, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcircuitbreaker',
            name='tension',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tensão'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='final_protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo Definitivo'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='interim_protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo Provisório'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.requestsenergycompany', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='requested_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.units', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='historicalunits',
            name='main_unit',
            field=models.BooleanField(default=False, verbose_name='Geradora'),
        ),
        migrations.AddField(
            model_name='historicalunits',
            name='unit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porcentagem de Rateio'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='final_protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo Definitivo'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='interim_protocol',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Protocolo Provisório'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.requestsenergycompany', verbose_name='Solicitação'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Solicitado por'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.units', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='units',
            name='main_unit',
            field=models.BooleanField(default=False, verbose_name='Geradora'),
        ),
        migrations.AddField(
            model_name='units',
            name='unit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porcentagem de Rateio'),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Corrente'),
        ),
        migrations.AlterField(
            model_name='circuitbreaker',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='historicalcircuitbreaker',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalcircuitbreaker',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Corrente'),
        ),
        migrations.AlterField(
            model_name='historicalcircuitbreaker',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Deletado'),
        ),
        migrations.AlterField(
            model_name='historicalrequestsenergycompany',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('D', 'Deferido'), ('I', 'Indeferido')], max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicalunits',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Fornecimento'),
        ),
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('D', 'Deferido'), ('I', 'Indeferido')], max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='units',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Fornecimento'),
        ),
        migrations.CreateModel(
            name='HistoricalResquestType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo de Solicitação',
                'verbose_name_plural': 'historical Tipos de Solicitação',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSituationEnergyCompany',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Situação da Concessionária de Energia',
                'verbose_name_plural': 'historical Situações da Concessionária de Energia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSupplyAdequance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Adequação de Fornecimento',
                'verbose_name_plural': 'historical Adequações de Fornecimento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.resquesttype', verbose_name='Tipo de Solicitação'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='engineering.resquesttype', verbose_name='Tipo de Solicitação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='situation',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.situationenergycompany', verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='situation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.situationenergycompany', verbose_name='Situação'),
        ),
        migrations.AddField(
            model_name='units',
            name='supply_adquance',
            field=models.ManyToManyField(blank=True, to='engineering.supplyadequance', verbose_name='Adequação de Fornecimento'),
        ),
    ]
