# Generated by Django 5.0.4 on 2024-11-12 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_resquesttype_situationenergycompany_supplyadequance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircuitBreaker',
        ),
        migrations.AlterModelOptions(
            name='historicalrequestsenergycompany',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Solicitação da Concessionária de Energia', 'verbose_name_plural': 'historical Solicitações da Concessionárias de Energia'},
        ),
        migrations.AlterModelOptions(
            name='requestsenergycompany',
            options={'verbose_name': 'Solicitação da Concessionária de Energia', 'verbose_name_plural': 'Solicitações da Concessionárias de Energia'},
        ),
        migrations.DeleteModel(
            name='HistoricalCircuitBreaker',
        ),
    ]
