# Generated by Django 5.0.4 on 2024-11-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_resquesttype_situationenergycompany_supplyadequance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CircuitBreaker',
        ),
        migrations.DeleteModel(
            name='HistoricalCircuitBreaker',
        ),
    ]
