# Generated by Django 5.0.4 on 2024-11-13 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0009_delete_circuitbreaker_and_more'),
        ('resolve_crm', '0027_alter_historicalproject_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
