# Generated by Django 5.0.4 on 2024-11-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0010_alter_units_project'),
        ('resolve_crm', '0031_alter_historicallead_funnel_alter_lead_funnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.project', verbose_name='Projeto'),
            preserve_default=False,
        ),
    ]
