# Generated by Django 5.0.4 on 2024-11-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0011_alter_requestsenergycompany_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrequestsenergycompany',
            name='situation',
        ),
        migrations.RemoveField(
            model_name='requestsenergycompany',
            name='situation',
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='situation',
            field=models.ManyToManyField(blank=True, to='engineering.situationenergycompany', verbose_name='Situação'),
        ),
    ]
