# Generated by Django 5.0.4 on 2024-11-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0012_remove_historicalrequestsenergycompany_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalunits',
            name='type',
            field=models.CharField(blank=True, choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], max_length=100, null=True, verbose_name='Tipo de Fornecimento'),
        ),
        migrations.AlterField(
            model_name='units',
            name='type',
            field=models.CharField(blank=True, choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], max_length=100, null=True, verbose_name='Tipo de Fornecimento'),
        ),
    ]
