# Generated by Django 5.0.4 on 2024-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0013_alter_historicalunits_type_alter_units_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='energycompany',
            options={'ordering': ['name'], 'verbose_name': 'Distribuidora de Energia', 'verbose_name_plural': 'Distribuidoras de Energia'},
        ),
        migrations.AlterModelOptions(
            name='requestsenergycompany',
            options={'ordering': ['-request_date'], 'verbose_name': 'Solicitação da Concessionária de Energia', 'verbose_name_plural': 'Solicitações da Concessionárias de Energia'},
        ),
        migrations.AlterModelOptions(
            name='resquesttype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Solicitação', 'verbose_name_plural': 'Tipos de Solicitação'},
        ),
        migrations.AlterModelOptions(
            name='situationenergycompany',
            options={'ordering': ['name'], 'verbose_name': 'Situação da Concessionária de Energia', 'verbose_name_plural': 'Situações da Concessionária de Energia'},
        ),
        migrations.AlterModelOptions(
            name='supplyadequance',
            options={'ordering': ['name'], 'verbose_name': 'Adequação de Fornecimento', 'verbose_name_plural': 'Adequações de Fornecimento'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'ordering': ['name'], 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
    ]
