# Generated by Django 5.0.4 on 2024-11-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0014_alter_energycompany_options_and_more'),
        ('resolve_crm', '0044_step_projectstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_energy_company', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
