# Generated by Django 5.0.4 on 2024-12-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0015_alter_requestsenergycompany_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunits',
            name='new_contract_number',
            field=models.BooleanField(default=False, verbose_name='Nova UC'),
        ),
        migrations.AddField(
            model_name='units',
            name='new_contract_number',
            field=models.BooleanField(default=False, verbose_name='Nova UC'),
        ),
    ]
