# Generated by Django 5.0.4 on 2024-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0016_historicalunits_new_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='bill_file',
            field=models.FileField(blank=True, null=True, upload_to='units-bills/', verbose_name='Arquivo da Fatura'),
        ),
    ]
