# Generated by Django 4.2.9 on 2025-04-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
        ('engineering', '0017_alter_units_bill_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CivilConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_responsibility', models.CharField(choices=[('C', 'Cliente'), ('F', 'Franquiado')], max_length=1, verbose_name='Work Responsibility')),
                ('repass_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Repass Value')),
                ('budget_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Budget Value')),
                ('service_description', models.TextField(verbose_name='Service Description')),
                ('shading_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Shading Percentage')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='civil_construction', to='resolve_crm.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Civil Construction',
                'verbose_name_plural': 'Civil Constructions',
                'ordering': ['project'],
            },
        ),
    ]
