# Generated by Django 4.2.9 on 2025-04-30 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_franchiseinstallment_margin_and_more'),
        ('engineering', '0018_civilconstruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilconstruction',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='civilconstruction',
            name='financial_records',
            field=models.ManyToManyField(blank=True, related_name='civil_construction', to='financial.financialrecord', verbose_name='Financial Recordies'),
        ),
        migrations.AddField(
            model_name='civilconstruction',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizada'), ('C', 'Cancelado'), ('EA', 'Em Andamento')], default='P', max_length=2, verbose_name='Status'),
        ),
    ]
