# Generated by Django 4.2.9 on 2025-05-02 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
        ('engineering', '0019_civilconstruction_deadline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='civilconstruction',
            options={'ordering': ['project'], 'verbose_name': 'Obra Civil', 'verbose_name_plural': 'Obras Civis'},
        ),
        migrations.AlterField(
            model_name='civilconstruction',
            name='budget_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Orçamento'),
        ),
        migrations.AlterField(
            model_name='civilconstruction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='civil_construction', to='resolve_crm.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='civilconstruction',
            name='repass_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Repasse'),
        ),
        migrations.AlterField(
            model_name='civilconstruction',
            name='service_description',
            field=models.TextField(verbose_name='Descrição do Serviço'),
        ),
        migrations.AlterField(
            model_name='civilconstruction',
            name='shading_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual de Sombreamento'),
        ),
        migrations.AlterField(
            model_name='civilconstruction',
            name='work_responsibility',
            field=models.CharField(choices=[('C', 'Cliente'), ('F', 'Franquiado')], max_length=1, verbose_name='Responsabilidade da Obra'),
        ),
    ]
