# Generated by Django 4.2.9 on 2025-05-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0020_alter_civilconstruction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequestsenergycompany',
            name='debit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Débito'),
        ),
        migrations.AddField(
            model_name='requestsenergycompany',
            name='debit_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Débito'),
        ),
        migrations.AlterField(
            model_name='historicalrequestsenergycompany',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('D', 'Deferido'), ('I', 'Indeferido')], default='S', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('D', 'Deferido'), ('I', 'Indeferido')], default='S', max_length=2, verbose_name='Status'),
        ),
    ]
