# Generated by Django 4.2.9 on 2025-05-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0021_historicalrequestsenergycompany_debit_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequestsenergycompany',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('D', 'Deferido'), ('I', 'Indeferido'), ('ID', 'Indeferido com Débito')], default='S', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='requestsenergycompany',
            name='status',
            field=models.CharField(choices=[('S', 'Solicitado'), ('D', 'Deferido'), ('I', 'Indeferido'), ('ID', 'Indeferido com Débito')], default='S', max_length=2, verbose_name='Status'),
        ),
    ]
