# Generated by Django 4.2.9 on 2025-05-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0022_alter_historicalrequestsenergycompany_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalunits',
            name='change_ownership',
            field=models.BooleanField(default=False, verbose_name='Troca de Titularidade'),
        ),
        migrations.AddField(
            model_name='units',
            name='change_ownership',
            field=models.BooleanField(default=False, verbose_name='Troca de Titularidade'),
        ),
    ]
