# Generated by Django 4.2.9 on 2025-05-17 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0023_historicalunits_change_ownership_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilconstruction',
            name='work_responsibility',
            field=models.CharField(choices=[('C', 'Cliente'), ('F', 'Franquia'), ('O', 'Centro de Operações')], max_length=1, verbose_name='Responsabilidade da Obra'),
        ),
    ]
