# Generated by Django 4.2.9 on 2025-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0024_alter_civilconstruction_work_responsibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilconstruction',
            name='is_customer_aware',
            field=models.BooleanField(default=False, verbose_name='Cliente ciente'),
        ),
    ]
