# Generated by Django 4.2.9 on 2025-05-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0025_civilconstruction_is_customer_aware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilconstruction',
            name='deadline',
        ),
        migrations.AddField(
            model_name='civilconstruction',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da Obra'),
        ),
        migrations.AddField(
            model_name='civilconstruction',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início da Obra'),
        ),
    ]
