# Generated by Django 4.2.9 on 2025-05-26 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0026_remove_civilconstruction_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilconstruction',
            name='shading_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Percentual de Sombreamento'),
        ),
    ]
