# Generated by Django 5.0.7 on 2024-09-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='squad_boards', to='core.board', verbose_name='Quadros'),
        ),
        migrations.AddField(
            model_name='squad',
            name='task_templates',
            field=models.ManyToManyField(blank=True, related_name='squad_task_templates', to='core.tasktemplates', verbose_name='Templates de Tarefa'),
        ),
    ]
