# Generated by Django 5.0.7 on 2024-07-29 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='branch_owners', to=settings.AUTH_USER_MODEL, verbose_name='Proprietários'),
        ),
    ]
