# Generated by Django 5.0.7 on 2024-09-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_squad_boards_squad_task_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='boards',
        ),
    ]
