# Generated by Django 5.0.7 on 2024-09-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_squad_boards'),
        ('core', '0002_historicalwebhook_tasktemplates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='task_templates',
            field=models.ManyToManyField(blank=True, related_name='squad_task_templates', to='core.tasktemplates', verbose_name='Templates de Tarefa'),
        ),
    ]
