# Generated by Django 5.0.7 on 2024-09-02 12:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalsquad_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Tipo de Usuário')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Tipo de Usuário',
                'verbose_name_plural': 'Tipos de Usuário',
            },
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cpf',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='first_document',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='person_type',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='second_document',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RG/Inscrição Estadual'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_document',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='user',
            name='person_type',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], max_length=2, null=True, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='user',
            name='second_document',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='RG/Inscrição Estadual'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1, verbose_name='Gênero'),
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,11}$')], verbose_name='Número de Telefone')),
                ('is_main', models.BooleanField(default=False, verbose_name='Principal?')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Número de Telefone',
                'verbose_name_plural': 'Números de Telefone',
            },
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='phone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.phonenumber', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.phonenumber', verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_types',
            field=models.ManyToManyField(to='accounts.usertype', verbose_name='Tipos de Usuário'),
        ),
    ]
