# Generated by Django 5.0.7 on 2024-09-20 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_squad_boards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='task_templates',
        ),
    ]
