# Generated by Django 5.0.7 on 2024-09-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_squad_task_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='squad',
            field=models.ManyToManyField(blank=True, related_name='squad_boards', to='accounts.squad', verbose_name='Squad'),
        ),
    ]
