# Generated by Django 5.0.7 on 2024-09-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usertype_remove_historicaluser_cpf_remove_user_cpf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.AddField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(related_name='customer_addresses', to='accounts.address', verbose_name='Endereços'),
        ),
    ]
