# Generated by Django 5.0.7 on 2024-09-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_squad_squad'),
        ('core', '0007_remove_board_squad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squad',
            name='squad',
        ),
        migrations.AddField(
            model_name='squad',
            name='boards',
            field=models.ManyToManyField(blank=True, related_name='squads', to='core.board', verbose_name='Quadro'),
        ),
    ]
