# Generated by Django 5.0.7 on 2024-09-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_historicaluser_address_remove_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='historicaladdress',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
    ]
