# Generated by Django 5.0.7 on 2024-10-11 14:10

from django.db import migrations


def create_user_types(apps, schema_editor):
    UserType = apps.get_model('accounts', 'UserType')
    UserType.objects.bulk_create([
        UserType(name='Fornecedor'),
        UserType(name='Cliente'),
        UserType(name='Funcionário'),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_squad_squad_squad_boards'),
    ]

    operations = [
        migrations.RunPython(create_user_types),
    ]