# Generated by Django 5.0.7 on 2024-09-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_address_is_deleted_historicaladdress_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='historicalrole',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='historicalsquad',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
        migrations.AddField(
            model_name='squad',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado?'),
        ),
    ]
