# Generated by Django 5.0.7 on 2024-10-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
            preserve_default=False,
        ),
    ]
