# Generated by Django 5.0.7 on 2024-10-18 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_historicaluser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['is_main', 'user__complete_name'], 'verbose_name': 'Número de Telefone', 'verbose_name_plural': 'Números de Telefone'},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='country_code',
            field=models.PositiveSmallIntegerField(default=55, verbose_name='Código do País'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Número de Telefone'),
        ),
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('country_code', 'phone_number')},
        ),
    ]
