# Generated by Django 5.0.7 on 2024-10-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_phonenumber_options_phonenumber_country_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ['-is_main', 'user__complete_name'], 'verbose_name': 'Número de Telefone', 'verbose_name_plural': 'Números de Telefone'},
        ),
    ]
