# Generated by Django 5.0.7 on 2024-10-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_branch_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['city', 'state', 'street', 'number'], 'verbose_name': 'Endereço', 'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='squad',
            options={'ordering': ['name'], 'verbose_name': 'Squad', 'verbose_name_plural': 'Squads'},
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Usuário', 'verbose_name_plural': 'Tipos de Usuário'},
        ),
    ]
