# Generated by Django 5.0.4 on 2024-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_address_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['complete_name', 'first_name', 'email'], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('C', 'CLT'), ('P', 'PJ')], max_length=1, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('C', 'CLT'), ('P', 'PJ')], max_length=1, null=True, verbose_name='Tipo de Contrato'),
        ),
    ]
