# Generated by Django 5.0.4 on 2024-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='first_document',
            field=models.CharField(db_index=True, default='', max_length=20, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_document',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
    ]
