# Generated by Django 5.0.4 on 2024-11-08 18:55

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_historicaluser_first_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='resignation_date',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='user_manager',
        ),
        migrations.RemoveField(
            model_name='user',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='resignation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_manager',
        ),
        migrations.AddField(
            model_name='branch',
            name='discount_allowed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto Permitido'),
        ),
        migrations.AddField(
            model_name='branch',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='branches', verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='branch',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porcentagem de Repasse'),
        ),
        migrations.AddField(
            model_name='department',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='department_owner', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='discount_allowed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto Permitido'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='picture',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Porcentagem de Repasse'),
        ),
        migrations.AddField(
            model_name='historicaldepartment',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gerente'),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='first_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, choices=[('C', 'CLT'), ('P', 'PJ')], max_length=1, null=True, verbose_name='Tipo de Contrato')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Unidade')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.department', verbose_name='Departamento')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role', verbose_name='Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('user_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='this_user_manager', to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['user__complete_name', 'user__first_name', 'user__email'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('contract_type', models.CharField(blank=True, choices=[('C', 'CLT'), ('P', 'PJ')], max_length=1, null=True, verbose_name='Tipo de Contrato')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Data de Admissão')),
                ('resignation_date', models.DateField(blank=True, null=True, verbose_name='Data de Demissão')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('branch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Unidade')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.department', verbose_name='Departamento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.role', verbose_name='Cargo')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('user_manager', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gerente')),
            ],
            options={
                'verbose_name': 'historical Funcionário',
                'verbose_name_plural': 'historical Funcionários',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
