# Generated by Django 5.0.4 on 2024-11-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_historicaluser_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='complete_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='complete_name',
            field=models.CharField(default='', max_length=255, verbose_name='Nome Completo'),
            preserve_default=False,
        ),
    ]
