# Generated by Django 5.0.4 on 2024-11-22 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse'),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse'),
        ),
    ]
