# Generated by Django 5.0.4 on 2024-11-25 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_branch_transfer_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='discount_allowed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Desconto Permitido'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse'),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='discount_allowed',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Desconto Permitido'),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse'),
        ),
    ]
