# Generated by Django 5.0.4 on 2024-12-03 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_branch_discount_allowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='area_code',
            field=models.PositiveSmallIntegerField(default=91, max_length=2, validators=[django.core.validators.RegexValidator('^\\d{2}$')], verbose_name='DDD'),
            preserve_default=False,
        ),
    ]
