# Generated by Django 5.0.4 on 2024-12-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_phonenumber_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together=set(),
        ),
    ]
