# Generated by Django 5.0.4 on 2024-12-04 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_phonenumber_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='area_code',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.RegexValidator('^\\d{2}$'), django.core.validators.MaxValueValidator(99)], verbose_name='DDD'),
        ),
    ]
