# Generated by Django 5.0.4 on 2024-12-09 11:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_phonenumber_area_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$')], verbose_name='Número de Telefone'),
        ),
    ]
