# Generated by Django 5.0.4 on 2025-01-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_branch_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='discount_allowed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Desconto Permitido'),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='discount_allowed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Desconto Permitido'),
        ),
    ]
