# Generated by Django 5.0.4 on 2025-01-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_branch_discount_allowed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Nome de Usuário'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Nome de Usuário'),
        ),
    ]
