# Generated by Django 5.0.4 on 2025-01-13 13:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_historicaluser_username_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='transfer_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('20.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentagem de Repasse'),
        ),
        migrations.AlterField(
            model_name='historicalbranch',
            name='transfer_percentage',
            field=models.DecimalField(decimal_places=4, default=Decimal('20.00'), max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentagem de Repasse'),
        ),
    ]
