# Generated by Django 5.0.4 on 2025-01-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_branch_transfer_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Senha'),
        ),
    ]
