# Generated by Django 5.0.4 on 2025-01-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_alter_historicaluser_password_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='related_branches',
            field=models.ManyToManyField(blank=True, related_name='related_users', to='accounts.branch', verbose_name='Unidades Relacionadas'),
        ),
    ]
