# Generated by Django 5.0.4 on 2025-01-18 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_employee_related_branches'),
        ('engineering', '0017_alter_units_bill_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='energy_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineering.energycompany', verbose_name='Companhia Elétrica'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='energy_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.energycompany', verbose_name='Companhia Elétrica'),
        ),
    ]
