# Generated by Django 5.0.4 on 2025-03-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_address_latitude_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True, verbose_name='Longitude'),
        ),
    ]
