# Generated by Django 5.0.4 on 2025-03-13 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,8}$')], verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='historicaladdress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,8}$')], verbose_name='CEP'),
        ),
    ]
