# Generated by Django 5.0.4 on 2025-03-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_alter_address_latitude_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='customer_addresses', to='accounts.address', verbose_name='Endereços'),
        ),
    ]
