# Generated by Django 4.2.9 on 2025-03-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_addresses'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['zip_code'], name='accounts_ad_zip_cod_8d1d98_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['country'], name='accounts_ad_country_344bc6_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['state'], name='accounts_ad_state_9aaef2_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['city'], name='accounts_ad_city_a5f6ae_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['neighborhood'], name='accounts_ad_neighbo_b603b4_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street'], name='accounts_ad_street_4956f5_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['number'], name='accounts_ad_number_fdb674_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['complement'], name='accounts_ad_complem_048e4b_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['latitude'], name='accounts_ad_latitud_de1269_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['longitude'], name='accounts_ad_longitu_0e8a94_idx'),
        ),
    ]
