# Generated by Django 4.2.9 on 2025-04-30 17:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_address_accounts_ad_zip_cod_8d1d98_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Margem de Repasse'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='margin',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), max_digits=5, verbose_name='Margem de Repasse'),
        ),
    ]
