# Generated by Django 4.2.9 on 2025-04-30 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_branch_margin_historicalbranch_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='marketing_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='Taxa de Marketing'),
        ),
        migrations.AddField(
            model_name='historicalbranch',
            name='marketing_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5, verbose_name='Taxa de Marketing'),
        ),
    ]
