# Generated by Django 4.2.9 on 2025-05-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_branch_marketing_tax_historicalbranch_marketing_tax'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_document'], name='accounts_us_first_d_f43999_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['second_document'], name='accounts_us_second__4a88de_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='accounts_us_email_74c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['complete_name'], name='accounts_us_complet_5eaeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='accounts_us_usernam_c0ea66_idx'),
        ),
    ]
