# Generated by Django 4.2.9 on 2025-07-19 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_user_accounts_us_first_d_f43999_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255, verbose_name='Endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='Método')),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True, verbose_name='User Agent')),
                ('ip', models.GenericIPAddressField(verbose_name='IP')),
                ('accessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Acessado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Acessos ao Endpoint',
                'verbose_name_plural': 'Acessos ao Endpoint',
                'ordering': ['-accessed_at'],
            },
        ),
    ]
