# Generated by Django 4.2.9 on 2025-07-29 14:07

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_endpointaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField(help_text='Use o primeiro dia do mês para representar o período da meta (ex: 01/08/2024 para Agosto de 2024).', verbose_name='Mês e Ano da Meta')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='O valor total que a unidade deve atingir no mês.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor da Meta')),
                ('achieved_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='O valor acumulado de vendas no mês. Atualizado automaticamente.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Valor Alcançado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('branch', models.ForeignKey(help_text='A unidade à qual esta meta se refere.', on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to='accounts.branch', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Meta Mensal',
                'verbose_name_plural': 'Metas Mensais',
                'ordering': ['-month_year', 'branch__name'],
                'unique_together': {('branch', 'month_year')},
            },
        ),
    ]
