# Generated by Django 4.2.9 on 2025-07-31 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_monthlygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='target_sales',
            field=models.PositiveIntegerField(default=100, help_text='O número total de vendas que a unidade deve alcançar no mês.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Vendas'),
            preserve_default=False,
        ),
    ]
