# Generated by Django 4.2.9 on 2025-07-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_monthlygoal_target_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='achieved_sales',
            field=models.PositiveIntegerField(default=0, help_text='O número de vendas que a unidade alcançou no mês.', verbose_name='Vendas Alcançadas'),
        ),
    ]
