# Generated by Django 4.2.9 on 2025-08-07 00:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_monthlygoal_achieved_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlygoal',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Fim do Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlygoal',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Início do Período'),
            preserve_default=False,
        ),
    ]
