# Generated by Django 5.0.1 on 2024-03-08 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_email_alter_user_email_squad'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['name'], 'verbose_name': 'Quadro', 'verbose_name_plural': 'Quadros'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['order'], 'verbose_name': 'Cartão', 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['order'], 'verbose_name': 'Coluna', 'verbose_name_plural': 'Colunas'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterField(
            model_name='lead',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Lead'),
        ),
    ]
