# Generated by Django 5.0.1 on 2024-03-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_card_column_alter_lead_responsible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('L', 'Leads'), ('T', 'Tarefas')], default='L', max_length=200, verbose_name='Tipo'),
            preserve_default=False,
        ),
    ]
