# Generated by Django 5.0.1 on 2024-03-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_board_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='notes',
        ),
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(choices=[('L', 'Leads'), ('T', 'Tarefas')], default='L', max_length=200, verbose_name='Tipo'),
        ),
    ]
