# Generated by Django 5.0.1 on 2024-07-16 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_attachment_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'E-mail'), ('sms', 'SMS')], max_length=10, verbose_name='Tipo de Contato')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Corpo')),
                ('sent_at', models.DateTimeField(verbose_name='Enviado em')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.lead', verbose_name='Contato')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
