# Generated by Django 5.0.7 on 2024-10-14 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0006_alter_schedule_address_alter_schedule_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_services.category', verbose_name='Categoria Principal'),
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
