# Generated by Django 5.0.7 on 2024-10-15 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0007_category_main_category_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Formulário')),
                ('campos', models.JSONField(blank=True, null=True, verbose_name='Campos')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Formulário',
                'verbose_name_plural': 'Formulários',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, null=True, verbose_name='Respostas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_services.forms', verbose_name='Formulário')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
    ]
