# Generated by Django 5.0.7 on 2024-10-15 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0011_alter_answer_created_by_alter_category_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
    ]
