# Generated by Django 5.0.7 on 2024-10-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0017_alter_deadline_hours_alter_historicaldeadline_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalschedule',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='deadline',
        ),
    ]
