# Generated by Django 5.0.7 on 2024-10-17 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0018_remove_historicalschedule_deadline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='schedule_agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Agente do Agendamento'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agente do Agendamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Agendamento'),
        ),
    ]
