# Generated by Django 5.0.7 on 2024-10-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0019_historicalschedule_schedule_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
    ]
