# Generated by Django 5.0.7 on 2024-10-28 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_types'),
        ('field_services', '0024_historicalschedule_schedule_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='address',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Endereço'),
            preserve_default=False,
        ),
    ]
