# Generated by Django 5.0.7 on 2024-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0025_historicalschedule_address_schedule_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
    ]
