# Generated by Django 5.0.4 on 2024-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0027_historicalschedule_execution_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resposta', 'verbose_name_plural': 'Respostas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='deadline',
            options={'ordering': ['name'], 'verbose_name': 'Prazo', 'verbose_name_plural': 'Prazos'},
        ),
        migrations.AlterModelOptions(
            name='forms',
            options={'ordering': ['name'], 'verbose_name': 'Formulário', 'verbose_name_plural': 'Formulários'},
        ),
        migrations.AlterModelOptions(
            name='rooftype',
            options={'ordering': ['name'], 'verbose_name': 'Tipo de Telhado', 'verbose_name_plural': 'Tipos de Telhados'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
