# Generated by Django 5.0.4 on 2024-11-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0028_alter_answer_options_alter_category_options_and_more'),
        ('resolve_crm', '0043_historicalproject_designer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_services', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
