# Generated by Django 5.0.4 on 2024-12-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0032_alter_blocktimeagent_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forms',
            name='service',
        ),
        migrations.RemoveField(
            model_name='historicalforms',
            name='service',
        ),
        migrations.AddField(
            model_name='historicalservice',
            name='form',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.forms', verbose_name='Formulário'),
        ),
        migrations.AddField(
            model_name='service',
            name='form',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='field_services.forms', verbose_name='Formulário'),
            preserve_default=False,
        ),
    ]
