# Generated by Django 5.0.4 on 2024-12-10 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0033_remove_forms_service_remove_historicalforms_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='field_services.schedule', verbose_name='Agendamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='schedule',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.schedule', verbose_name='Agendamento'),
        ),
    ]
