# Generated by Django 5.0.4 on 2024-12-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0034_answer_schedule_historicalanswer_schedule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='freetimeagent',
            name='unique_free_time_agent',
        ),
    ]
