# Generated by Django 5.0.4 on 2024-12-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0038_remove_freetimeagent_free_time_agent_and_more'),
        ('logistics', '0019_alter_saleproduct_commercial_proposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='products',
            field=models.ManyToManyField(blank=True, to='logistics.product', verbose_name='Produtos'),
        ),
    ]
