# Generated by Django 5.0.4 on 2024-12-13 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0038_remove_freetimeagent_free_time_agent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
