# Generated by Django 5.0.4 on 2024-12-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0043_merge_20241218_1609'),
        ('field_services', '0043_remove_historicalagentroute_agent_and_more'),
    ]

    operations = [
    ]
