# Generated by Django 5.0.4 on 2024-12-30 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0044_alter_historicalschedule_status_and_more'),
        ('field_services', '0044_merge_20241230_1120'),
    ]

    operations = [
    ]
