# Generated by Django 5.0.4 on 2024-12-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0045_merge_20241230_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='hours',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='historicaldeadline',
            name='hours',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Horas'),
        ),
    ]
