# Generated by Django 5.0.4 on 2024-12-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0046_alter_deadline_hours_alter_historicaldeadline_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='schedule_end_date',
            field=models.DateField(default='2025-01-25', verbose_name='Data de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_end_date',
            field=models.DateField(default='2025-01-25', verbose_name='Data de Fim'),
            preserve_default=False,
        ),
    ]
