# Generated by Django 5.0.4 on 2024-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0048_formfile_historicalformfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfile',
            name='field_id',
            field=models.CharField(max_length=40, verbose_name='ID do Campo'),
        ),
        migrations.AlterField(
            model_name='historicalformfile',
            name='field_id',
            field=models.CharField(max_length=40, verbose_name='ID do Campo'),
        ),
    ]
