# Generated by Django 5.0.4 on 2025-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0049_alter_formfile_field_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfile',
            name='field_id',
            field=models.CharField(max_length=50, verbose_name='ID do Campo'),
        ),
        migrations.AlterField(
            model_name='historicalformfile',
            name='field_id',
            field=models.CharField(max_length=45, verbose_name='ID do Campo'),
        ),
        migrations.CreateModel(
            name='HistoricalServiceOpinion',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'historical Opinião do Serviço',
                'verbose_name_plural': 'historical Opiniões do Serviço',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_services.service', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Opinião do Serviço',
                'verbose_name_plural': 'Opiniões do Serviço',
                'ordering': ['-created_at'],
            },
        ),
    ]
