# Generated by Django 5.0.4 on 2025-01-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0049_alter_formfile_field_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfile',
            name='field_id',
            field=models.CharField(max_length=50, verbose_name='ID do Campo'),
        ),
        migrations.AlterField(
            model_name='historicalformfile',
            name='field_id',
            field=models.CharField(max_length=50, verbose_name='ID do Campo'),
        ),
    ]
