# Generated by Django 5.0.4 on 2025-01-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0050_alter_formfile_field_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalserviceopinion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Parecer do Serviço', 'verbose_name_plural': 'historical Pareceres do Serviço'},
        ),
        migrations.AlterModelOptions(
            name='serviceopinion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Parecer do Serviço', 'verbose_name_plural': 'Pareceres do Serviço'},
        ),
        migrations.AlterField(
            model_name='historicalformfile',
            name='field_id',
            field=models.CharField(max_length=50, verbose_name='ID do Campo'),
        ),
    ]
