# Generated by Django 5.0.4 on 2025-01-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0051_alter_historicalserviceopinion_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='campos',
            new_name='fields',
        ),
        migrations.RenameField(
            model_name='historicalforms',
            old_name='campos',
            new_name='fields',
        ),
    ]
