# Generated by Django 5.0.4 on 2025-01-03 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0052_rename_campos_forms_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='service_opinion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.serviceopinion', verbose_name='Parecer do Serviço'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='service_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='field_services.serviceopinion', verbose_name='Parecer do Serviço'),
        ),
    ]
