# Generated by Django 5.0.4 on 2025-01-05 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0053_historicalschedule_service_opinion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='final_service_opinion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.serviceopinion', verbose_name='Parecer Final do Serviço'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='final_service_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_service_opinion', to='field_services.serviceopinion', verbose_name='Parecer Final do Serviço'),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
    ]
