# Generated by Django 5.0.4 on 2025-01-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0054_historicalschedule_final_service_opinion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='parent_schedules',
            field=models.ManyToManyField(blank=True, related_name='child_schedules', to='field_services.schedule', verbose_name='Agendamentos Pai'),
        ),
    ]
