# Generated by Django 5.0.4 on 2025-01-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_column_column_type_historicalcolumn_column_type_and_more'),
        ('field_services', '0055_schedule_parent_schedules'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='core.attachment', verbose_name='Anexos'),
        ),
    ]
