# Generated by Django 5.0.4 on 2025-01-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0056_schedule_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserviceopinion',
            name='is_final_opinion',
            field=models.BooleanField(default=False, verbose_name='Parecer Final'),
        ),
        migrations.AddField(
            model_name='serviceopinion',
            name='is_final_opinion',
            field=models.BooleanField(default=False, verbose_name='Parecer Final'),
        ),
    ]
