# Generated by Django 5.0.4 on 2025-01-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0057_historicalserviceopinion_is_final_opinion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='Protocolo'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='protocol',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Protocolo'),
        ),
    ]
