# Generated by Django 5.0.4 on 2025-01-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0058_historicalschedule_protocol_schedule_protocol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_schedule', 'Can view all schedule')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
