# Generated by Django 5.0.4 on 2025-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0059_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chegou em'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='step',
            field=models.IntegerField(default=1, verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Chegou em'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='step',
            field=models.IntegerField(default=1, verbose_name='Etapa'),
        ),
    ]
