# Generated by Django 5.0.4 on 2025-02-07 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0060_historicalschedule_arrived_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_schedule', 'Can view all schedule'), ('view_agent_info', 'Can view agent info')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
