# Generated by Django 5.0.4 on 2025-02-08 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0061_alter_schedule_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='final_service_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_service_opinion', to='field_services.serviceopinion', verbose_name='Parecer Final do Serviço'),
        ),
    ]
