# Generated by Django 5.0.4 on 2025-02-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0061_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='status_choices',
            field=models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em Andamento'), ('C', 'Concluído'), ('CA', 'Cancelado')], default='P', max_length=50, verbose_name='Status do Agente'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='status_choices',
            field=models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em Andamento'), ('C', 'Concluído'), ('CA', 'Cancelado')], default='P', max_length=50, verbose_name='Status do Agente'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='final_service_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_service_opinion', to='field_services.serviceopinion', verbose_name='Parecer Final do Serviço'),
        ),
    ]
