# Generated by Django 5.0.4 on 2025-02-10 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0062_alter_schedule_final_service_opinion'),
        ('field_services', '0062_historicalschedule_status_choices_and_more'),
    ]

    operations = [
    ]
