# Generated by Django 5.0.4 on 2025-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0063_merge_20250210_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalschedule',
            old_name='status_choices',
            new_name='agent_status',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='status_choices',
            new_name='agent_status',
        ),
    ]
