# Generated by Django 5.0.4 on 2025-02-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0064_rename_status_choices_historicalschedule_agent_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_schedule', 'Can view all schedule'), ('view_agent_info', 'Can view agent info'), ('view_service_opinion', 'Can view service opinion'), ('can_change_service', 'Can change service')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
