# Generated by Django 5.0.4 on 2025-02-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_branch_energy_company_and_more'),
        ('field_services', '0065_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Unidade'),
        ),
    ]
