# Generated by Django 5.0.4 on 2025-02-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0066_historicalschedule_branch_schedule_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Confirmado', 'Confirmado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
    ]
