# Generated by Django 5.0.4 on 2025-02-21 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0067_alter_historicalschedule_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalserviceopinion',
            name='is_aproved',
            field=models.BooleanField(default=False, verbose_name='Status Aprovado'),
        ),
        migrations.AddField(
            model_name='historicalserviceopinion',
            name='is_exchangeable',
            field=models.BooleanField(default=False, verbose_name='É modificável'),
        ),
        migrations.AddField(
            model_name='serviceopinion',
            name='is_aproved',
            field=models.BooleanField(default=False, verbose_name='Status Aprovado'),
        ),
        migrations.AddField(
            model_name='serviceopinion',
            name='is_exchangeable',
            field=models.BooleanField(default=False, verbose_name='É modificável'),
        ),
    ]
