# Generated by Django 5.0.4 on 2025-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0069_alter_schedule_customer'),
        ('resolve_crm', '0073_remove_lead_inspections'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='leads',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='resolve_crm.lead', verbose_name='Leads'),
        ),
    ]
