# Generated by Django 5.0.4 on 2025-03-06 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_branch_energy_company_and_more'),
        ('field_services', '0070_schedule_leads'),
        ('resolve_crm', '0077_alter_comercialproposal_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='costumer', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='field_services', to='resolve_crm.project', verbose_name='Projeto'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agente de Campo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_creator', to=settings.AUTH_USER_MODEL, verbose_name='Criador do Agendamento'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='field_services.service', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service_opinion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='field_services.serviceopinion', verbose_name='Parecer do Serviço'),
        ),
    ]
