# Generated by Django 5.0.4 on 2025-03-12 18:24

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0071_alter_schedule_address_alter_schedule_branch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRoute',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Horário de Início')),
                ('end_time', models.DateTimeField(verbose_name='Horário de Fim')),
                ('start_lat_long', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude e Longitude de Início')),
                ('end_lat_long', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude e Longitude de Fim')),
                ('status', models.CharField(choices=[('I', 'Iniciada'), ('C', 'Concluído'), ('CA', 'Cancelado')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.schedule', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'historical Rota',
                'verbose_name_plural': 'historical Rotas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Horário de Início')),
                ('end_time', models.DateTimeField(verbose_name='Horário de Fim')),
                ('start_lat_long', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude e Longitude de Início')),
                ('end_lat_long', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude e Longitude de Fim')),
                ('status', models.CharField(choices=[('I', 'Iniciada'), ('C', 'Concluído'), ('CA', 'Cancelado')], max_length=50, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agente')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_services.schedule', verbose_name='Agendamento')),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-created_at'],
            },
        ),
    ]
