# Generated by Django 4.2.9 on 2025-03-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0072_historicalroute_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='protocol',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Protocolo'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_date'], name='field_servi_schedul_0814a2_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['created_at'], name='field_servi_created_634689_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['branch'], name='field_servi_branch__bc266c_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status'], name='field_servi_status_5f2b2a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_agent'], name='field_servi_schedul_f44e95_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['schedule_date', 'schedule_agent'], name='field_servi_schedul_0bcfca_idx'),
        ),
    ]
