# Generated by Django 4.2.9 on 2025-03-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('field_services', '0072_historicalroute_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos'),
        ),
    ]
