# Generated by Django 4.2.9 on 2025-03-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0073_alter_schedule_protocol_and_more'),
        ('field_services', '0073_service_groups'),
    ]

    operations = [
    ]
