# Generated by Django 4.2.9 on 2025-04-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0074_merge_20250327_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-created_at'], 'permissions': [('view_all_schedule', 'Can view all schedule'), ('view_agent_info', 'Can view agent info'), ('view_service_opinion', 'Can view service opinion'), ('can_change_service', 'Can change service'), ('can_see_admin_schedules', 'Can see admin schedules')], 'verbose_name': 'Agendamento', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
