# Generated by Django 4.2.9 on 2025-05-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0075_alter_schedule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor'),
        ),
    ]
