# Generated by Django 4.2.9 on 2025-05-15 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_services', '0076_historicalschedule_value_schedule_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='final_service_opinion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Parecer Final'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='final_service_opinion_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Parecer Final'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='final_service_opinion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Parecer Final'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='final_service_opinion_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_service_opinions', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Parecer Final'),
        ),
    ]
