# Generated by Django 4.2.9 on 2025-05-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0077_historicalschedule_final_service_opinion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='deadline',
            field=models.DurationField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='deadline',
            field=models.DurationField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
