# Generated by Django 4.2.9 on 2025-05-19 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_services', '0078_historicalschedule_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='categories', to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
    ]
