# Generated by Django 4.2.9 on 2025-05-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0079_alter_category_members'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blocktimeagent',
            index=models.Index(fields=['agent', 'start_date', 'end_date'], name='field_servi_agent_i_728af9_idx'),
        ),
        migrations.AddIndex(
            model_name='blocktimeagent',
            index=models.Index(fields=['agent', 'start_time', 'end_time'], name='field_servi_agent_i_8006bd_idx'),
        ),
    ]
