# Generated by Django 4.2.9 on 2025-05-26 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_services', '0080_blocktimeagent_field_servi_agent_i_728af9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocktimeagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_times', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='freetimeagent',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_times', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
    ]
