# Generated by Django 4.2.9 on 2025-05-31 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0081_alter_blocktimeagent_agent_alter_freetimeagent_agent'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['project', 'service'], name='field_servi_project_e2f46b_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['final_service_opinion'], name='field_servi_final_s_5634bb_idx'),
        ),
    ]
