# Generated by Django 4.2.9 on 2025-05-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0082_schedule_field_servi_project_e2f46b_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['project', '-created_at'], name='field_servi_project_30fdc1_idx'),
        ),
    ]
