# Generated by Django 4.2.9 on 2025-06-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0083_schedule_field_servi_project_30fdc1_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='severity',
            field=models.CharField(blank=True, choices=[('A', 'Baixa'), ('B', 'Média'), ('C', 'Alta')], max_length=50, null=True, verbose_name='Prioridade'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='severity',
            field=models.CharField(blank=True, choices=[('A', 'Baixa'), ('B', 'Média'), ('C', 'Alta')], max_length=50, null=True, verbose_name='Prioridade'),
        ),
    ]
