# Generated by Django 4.2.9 on 2025-06-13 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_services', '0084_historicalschedule_severity_schedule_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='requester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_requester', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante'),
        ),
    ]
