# Generated by Django 4.2.9 on 2025-07-23 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0085_historicalschedule_requester_schedule_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='datalogger_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Datalogger'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='inverter_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Inversor'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='datalogger_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Datalogger'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='inverter_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Inversor'),
        ),
    ]
