# Generated by Django 4.2.9 on 2025-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0086_historicalschedule_datalogger_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
