# Generated by Django 4.2.9 on 2025-08-09 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('field_services', '0087_historicalschedule_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='planta',
            field=models.TextField(blank=True, null=True, verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='solarz',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50, null=True, verbose_name='Solarz'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='planta',
            field=models.TextField(blank=True, null=True, verbose_name='Planta'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='solarz',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=50, null=True, verbose_name='Solarz'),
        ),
        migrations.CreateModel(
            name='HistoricalFormAnswer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True, verbose_name='Resposta')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.schedule', verbose_name='Agendamento')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'historical Resposta de Formulário',
                'verbose_name_plural': 'historical Respostas de Formulário',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FormAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.JSONField(blank=True, null=True, verbose_name='Resposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field_services.schedule', verbose_name='Agendamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Resposta de Formulário',
                'verbose_name_plural': 'Respostas de Formulário',
                'ordering': ['-created_at'],
            },
        ),
    ]
