# Generated by Django 4.2.9 on 2025-08-20 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0088_historicalschedule_planta_historicalschedule_solarz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='financiers_voucher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voucher do Financiador'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='financiers_voucher',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Voucher do Financiador'),
        ),
    ]
