# Generated by Django 5.0.4 on 2025-01-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='image',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default=1, upload_to='media', verbose_name='Arquivo'),
            preserve_default=False,
        ),
    ]
