# Generated by Django 5.0.4 on 2025-01-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_app', '0004_remove_media_image_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='discounts', verbose_name='Banner'),
        ),
    ]
