# Generated by Django 5.0.7 on 2024-10-11 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_types'),
        ('inspections', '0001_initial'),
        ('logistics', '0002_projectmaterials'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome da Categoria')),
                ('squads', models.ManyToManyField(blank=True, related_name='categories', to='accounts.squad', verbose_name='Squads')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_safelead', models.CharField(max_length=50, unique=True, verbose_name='ID Safelead')),
                ('telephone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('date', models.DateField(verbose_name='Data')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('comercial_observation', models.TextField(blank=True, null=True, verbose_name='Observação Comercial')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor', to=settings.AUTH_USER_MODEL, verbose_name='Contratante')),
                ('inverter_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inverter_model', to='logistics.materials', verbose_name='Modelo do Inversor')),
                ('module_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_model', to='logistics.materials', verbose_name='Modelo do Módulo')),
                ('saler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saler', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveyor', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='accounts.branch', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome do Serviço')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
