# Generated by Django 5.0.7 on 2024-10-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_schedule_project'),
        ('resolve_crm', '0007_alter_contractsubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
