# Generated by Django 5.0.7 on 2024-10-13 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_user_types'),
        ('inspections', '0005_schedule_address_schedule_agent_schedule_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='accounts.address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Agente'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='inspections.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='inspections.service', verbose_name='Serviço'),
        ),
    ]
