# Generated by Django 5.0.7 on 2024-10-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_deadline_historicalservice_deadline_service_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='historicaldeadline',
            name='hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas'),
        ),
    ]
