# Generated by Django 5.0.7 on 2024-10-19 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_historicalschedule_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='deadline',
            name='hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='historicaldeadline',
            name='hours',
            field=models.TimeField(blank=True, null=True, verbose_name='Horas'),
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='schedule_agent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Agente de Campo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agente de Campo'),
        ),
    ]
