# Generated by Django 5.0.7 on 2024-10-21 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_remove_category_squads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
        migrations.AddField(
            model_name='category',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Membros'),
        ),
    ]
