# Generated by Django 5.0.7 on 2024-10-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0023_remove_category_users_category_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='schedule_end_time',
            field=models.TimeField(default='13:00:00', verbose_name='Horário de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='schedule_start_time',
            field=models.TimeField(default='13:00:00', verbose_name='Horário de Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_end_time',
            field=models.TimeField(default='13:00:00', verbose_name='Horário de Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_start_time',
            field=models.TimeField(default='13:00', verbose_name='Horário de Início'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalschedule',
            name='schedule_date',
            field=models.DateField(verbose_name='Data do Agendamento'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_date',
            field=models.DateField(verbose_name='Data do Agendamento'),
        ),
    ]
