# Generated by Django 5.0.7 on 2024-11-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0026_alter_historicalschedule_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalschedule',
            name='execution_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução Finalizada em'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução Iniciada em'),
        ),
        migrations.AddField(
            model_name='historicalschedule',
            name='going_to_location_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Indo para o Local em'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='execution_finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução Finalizada em'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='execution_started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Execução Iniciada em'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='going_to_location_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Indo para o Local em'),
        ),
    ]
