# Generated by Django 5.0.4 on 2024-11-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0029_alter_schedule_project'),
        ('resolve_crm', '0044_step_projectstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_services', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
