# Generated by Django 5.0.4 on 2024-12-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0031_blocktimeagent_freetimeagent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocktimeagent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bloqueio de Horário', 'verbose_name_plural': 'Bloqueios de Horário'},
        ),
        migrations.AlterModelOptions(
            name='historicalblocktimeagent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Bloqueio de Horário', 'verbose_name_plural': 'historical Bloqueios de Horário'},
        ),
    ]
