# Generated by Django 5.0.4 on 2024-12-11 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0035_remove_freetimeagent_unique_free_time_agent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='freetimeagent',
            constraint=models.UniqueConstraint(fields=('agent', 'day_of_week'), name='unique_free_time_agent'),
        ),
    ]
