# Generated by Django 5.0.4 on 2024-12-16 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0040_agentroute_historicalagentroute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agente de Campo'),
        ),
    ]
