# Generated by Django 5.0.4 on 2024-12-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0041_alter_schedule_schedule_agent'),
        ('resolve_crm', '0048_remove_historicalproject_id_plant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='field_services', to='resolve_crm.project', verbose_name='Projeto'),
        ),
    ]
