# Generated by Django 5.0.4 on 2024-12-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0042_alter_schedule_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalagentroute',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='historicalagentroute',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalagentroute',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='AgentRoute',
        ),
        migrations.DeleteModel(
            name='HistoricalAgentRoute',
        ),
    ]
