# Generated by Django 5.0.4 on 2024-12-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0040_alter_schedule_schedule_agent'),
        ('inspections', '0042_alter_schedule_project'),
    ]

    operations = [
    ]
