# Generated by Django 5.0.4 on 2024-12-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0043_remove_historicalagentroute_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalschedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Confirmado', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=50, verbose_name='Status'),
        ),
    ]
