# Generated by Django 5.0.4 on 2025-01-02 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0049_alter_formfile_field_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='campos',
            new_name='fields',
        ),
        migrations.RenameField(
            model_name='historicalforms',
            old_name='campos',
            new_name='fields',
        ),
    ]
