# Generated by Django 5.0.7 on 2024-09-19 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_board_statuses_remove_historicaltask_status_and_more'),
        ('resolve_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='board',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='status',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='board',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='historicallead',
            name='column',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.column', verbose_name='Coluna'),
        ),
        migrations.AddField(
            model_name='lead',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='core.column', verbose_name='Coluna'),
        ),
    ]
