# Generated by Django 5.0.7 on 2024-09-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
