# Generated by Django 5.0.7 on 2024-08-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalsquad_squad'),
        ('core', '0003_boardtemplate_board_branch_column_order_and_more'),
        ('resolve_crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='boards',
        ),
        migrations.RemoveField(
            model_name='historicalcolumn',
            name='board',
        ),
        migrations.RemoveField(
            model_name='column',
            name='board',
        ),
        migrations.DeleteModel(
            name='BoardTemplate',
        ),
        migrations.RemoveField(
            model_name='historicalboard',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='historicalboard',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalboardtemplate',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcolumn',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsquad',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='historicalsquad',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsquad',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='squad',
            name='members',
        ),
        migrations.AlterField(
            model_name='lead',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.squad', verbose_name='Squad'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='squad',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.squad', verbose_name='Squad'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='column',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.column', verbose_name='Coluna'),
        ),
        migrations.AddField(
            model_name='lead',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards_leads', to='core.column', verbose_name='Coluna'),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='HistoricalBoard',
        ),
        migrations.DeleteModel(
            name='HistoricalBoardTemplate',
        ),
        migrations.DeleteModel(
            name='HistoricalColumn',
        ),
        migrations.DeleteModel(
            name='HistoricalSquad',
        ),
        migrations.DeleteModel(
            name='Squad',
        ),
    ]
