# Generated by Django 5.0.7 on 2024-08-09 19:15

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0002_remove_board_branch_remove_squad_boards_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead', models.CharField(max_length=255)),
                ('kwp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('monthly_generation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi_years', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payback_graph', models.TextField()),
                ('simulation_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('financing_options', models.TextField()),
                ('current_year_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_month_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generator_year_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('generator_month_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('annual_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_savings', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submit_datetime', models.DateTimeField(verbose_name='Data e hora do envio')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], max_length=1, verbose_name='Status do envio')),
                ('due_date', models.DateField(verbose_name='Prazo para assinatura')),
                ('link', models.URLField(verbose_name='Link para assinatura')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('start_datetime', models.DateTimeField(verbose_name='Data de Início')),
                ('end_datetime', models.DateTimeField(verbose_name='Data de Término')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('banner', models.ImageField(upload_to='resolve_crm/img/marketing_campaign/', verbose_name='Banner')),
            ],
            options={
                'verbose_name': 'Campanha de Marketing',
                'verbose_name_plural': 'Campanhas de Marketing',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSale',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], max_length=1, verbose_name='Status da Venda')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.contractsubmission', verbose_name='Contrato')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.lead', verbose_name='Lead')),
                ('proposal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.comercialproposal', verbose_name='Proposta Comercial')),
            ],
            options={
                'verbose_name': 'historical Venda',
                'verbose_name_plural': 'historical Vendas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceito'), ('R', 'Recusado')], max_length=1, verbose_name='Status da Venda')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.contractsubmission', verbose_name='Contrato')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.lead', verbose_name='Lead')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.comercialproposal', verbose_name='Proposta Comercial')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
    ]
