# Generated by Django 5.0.7 on 2024-09-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_squad_task_templates'),
        ('resolve_crm', '0002_alter_historicallead_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='type',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], help_text='Pessoa Física ou Jurídica?', max_length=200, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='lead_addresses', to='accounts.address', verbose_name='Endereços'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='type',
            field=models.CharField(blank=True, choices=[('PF', 'Pessoa Física'), ('PJ', 'Pessoa Jurídica')], help_text='Pessoa Física ou Jurídica?', max_length=200, null=True, verbose_name='Tipo'),
        ),
    ]
