# Generated by Django 5.0.7 on 2024-08-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0003_comercialproposal_contractsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2024-08-15 17:34:29.148330', editable=False, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2024-08-15 17:34:29.148330', editable=False, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-08-15 17:34:29.148330', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-08-15 17:34:29.148330', verbose_name='Criado em'),
            preserve_default=False,
        ),
    ]
