# Generated by Django 5.0.7 on 2024-09-23 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0003_alter_historicallead_type_alter_lead_addresses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.marketingcampaign', verbose_name='Campanha de Marketing'),
        ),
    ]
