# Generated by Django 5.0.7 on 2024-09-23 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0005_alter_historicalunits_account_number_and_more'),
        ('resolve_crm', '0004_alter_sale_marketing_campaign'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Projeto Completo'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='kwp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='kWp'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='project_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Projeto'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, null=True, verbose_name='Status do Projeto'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], max_length=50, null=True, verbose_name='Tipo de Fornecimento'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='is_sale',
            field=models.BooleanField(default=True, verbose_name='Pré-venda'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Projetista'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='project',
            name='homologator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homologator_projects', to=settings.AUTH_USER_MODEL, verbose_name='Homologador'),
        ),
        migrations.AlterField(
            model_name='project',
            name='instaled_circuit_breaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instaled_circuit_breaker', to='engineering.circuitbreaker', verbose_name='Disjuntor Instalado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Projeto Completo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='kwp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='kWp'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_circuit_breaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_circuit_breaker', to='engineering.circuitbreaker', verbose_name='Disjuntor do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='registered_circuit_breaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_circuit_breaker', to='engineering.circuitbreaker', verbose_name='Disjuntor Cadastrado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, null=True, verbose_name='Status do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supply_type',
            field=models.CharField(blank=True, choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], max_length=50, null=True, verbose_name='Tipo de Fornecimento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_sale',
            field=models.BooleanField(default=True, verbose_name='Pré-venda'),
        ),
    ]
