# Generated by Django 5.0.7 on 2024-08-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0004_historicallead_created_at_historicaltask_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='byname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apelido'),
        ),
        migrations.AddField(
            model_name='lead',
            name='byname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apelido'),
        ),
    ]
