# Generated by Django 5.0.7 on 2024-10-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0005_alter_historicalproject_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='funnel',
            field=models.CharField(blank=True, choices=[('C', 'Quente'), ('P', 'Moderado'), ('N', 'Negociação')], max_length=200, null=True, verbose_name='Funil'),
        ),
        migrations.AddField(
            model_name='lead',
            name='funnel',
            field=models.CharField(blank=True, choices=[('C', 'Quente'), ('P', 'Moderado'), ('N', 'Negociação')], max_length=200, null=True, verbose_name='Funil'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='contract_number',
            field=models.CharField(editable=False, max_length=20, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='signature_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='P', max_length=2, verbose_name='Status da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='contract_number',
            field=models.CharField(editable=False, max_length=20, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='signature_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='P', max_length=2, verbose_name='Status da Venda'),
        ),
    ]
