# Generated by Django 5.0.7 on 2024-08-19 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0005_historicallead_byname_lead_byname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='historicallead',
            name='squad',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='squad',
        ),
    ]
