# Generated by Django 5.0.7 on 2024-10-11 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0006_historicallead_funnel_lead_funnel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractsubmission',
            options={'verbose_name': 'Envio de Contrato', 'verbose_name_plural': 'Envios de Contrato'},
        ),
        migrations.AlterModelOptions(
            name='marketingcampaign',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'Campanha de Marketing', 'verbose_name_plural': 'Campanhas de Marketing'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
