# Generated by Django 5.0.7 on 2024-09-02 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usertype_remove_historicaluser_cpf_remove_user_cpf_and_more'),
        ('contracts', '0001_initial'),
        ('resolve_crm', '0006_remove_historicallead_responsible_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='borrower',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Tomador'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='branch',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='contract_date',
            field=models.DateField(default='2024-09-01', verbose_name='Data do Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='contract_number',
            field=models.CharField(default='', max_length=20, verbose_name='Número do Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2024-09-01 00:00:00.000000', editable=False, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='customer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='document_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Documento'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='document_situation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Situação do Documento'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='document_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='', max_length=2, verbose_name='Status do Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='financial_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Financeira'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='financial_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('PA', 'Parcial'), ('L', 'Liquidado')], default='', max_length=2, verbose_name='Status Financeiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='homologator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Homologador'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='is_completed_document',
            field=models.BooleanField(blank=True, null=True, verbose_name='Documento Completo'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='is_completed_financial',
            field=models.BooleanField(blank=True, null=True, verbose_name='Financeiro Completo'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.marketingcampaign', verbose_name='Campanha de Marketing'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='project_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor do Projeto'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='sales_manager',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de Vendas'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='sales_supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor de Vendas'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='seller',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='borrower',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='borrower_sales', to=settings.AUTH_USER_MODEL, verbose_name='Tomador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.branch', verbose_name='Unidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='contract_date',
            field=models.DateField(default='2024-09-01', verbose_name='Data do Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='contract_number',
            field=models.CharField(default='', max_length=20, verbose_name='Número do Contrato'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-01 00:00:00.000000', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='document_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Documento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='document_situation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Situação do Documento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='document_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='', max_length=2, verbose_name='Status do Documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='financial_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão Financeira'),
        ),
        migrations.AddField(
            model_name='sale',
            name='financial_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('PA', 'Parcial'), ('L', 'Liquidado')], default='', max_length=2, verbose_name='Status Financeiro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='homologator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homologator_sales', to=settings.AUTH_USER_MODEL, verbose_name='Homologador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='is_completed_document',
            field=models.BooleanField(blank=True, null=True, verbose_name='Documento Completo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_completed_financial',
            field=models.BooleanField(blank=True, null=True, verbose_name='Financeiro Completo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='marketing_campaign',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.marketingcampaign', verbose_name='Campanha de Marketing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='project_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor do Projeto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_manager',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='manager_sales', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de Vendas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sales_supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_sales', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor de Vendas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='seller_sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='resolve_crm/sale_documents/', verbose_name='Documento')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('R', 'Reprovado')], max_length=2, verbose_name='Status')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.documenttype', verbose_name='Tipo de Documento')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Documento da Venda',
                'verbose_name_plural': 'Documentos das Vendas',
            },
        ),
        migrations.DeleteModel(
            name='ComercialProposal',
        ),
    ]
