# Generated by Django 5.0.7 on 2024-10-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0007_alter_contractsubmission_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='financier',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='financier',
        ),
        migrations.RemoveField(
            model_name='historicalfinancier',
            name='address',
        ),
        migrations.RemoveField(
            model_name='historicalfinancier',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpayment',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentinstallment',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalpaymentinstallment',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='paymentinstallment',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Financier',
        ),
        migrations.DeleteModel(
            name='HistoricalFinancier',
        ),
        migrations.DeleteModel(
            name='HistoricalPayment',
        ),
        migrations.DeleteModel(
            name='HistoricalPaymentInstallment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PaymentInstallment',
        ),
    ]
