# Generated by Django 5.0.7 on 2024-09-05 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_historicaluser_address_remove_user_address_and_more'),
        ('resolve_crm', '0008_historicallead_customer_lead_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallead',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='address',
        ),
        migrations.AddField(
            model_name='historicallead',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='first_document',
            field=models.CharField(default='', max_length=20, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallead',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='sdr',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='SDR'),
        ),
        migrations.AddField(
            model_name='historicallead',
            name='second_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/IE'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.lead', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='addresses',
            field=models.ManyToManyField(related_name='lead_addresses', to='accounts.address', verbose_name='Endereços'),
        ),
        migrations.AddField(
            model_name='lead',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_document',
            field=models.CharField(default='', max_length=20, verbose_name='CPF/CNPJ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='lead',
            name='sdr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_sdr', to=settings.AUTH_USER_MODEL, verbose_name='SDR'),
        ),
        migrations.AddField(
            model_name='lead',
            name='second_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/IE'),
        ),
        migrations.AddField(
            model_name='sale',
            name='lead',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='lead_sales', to='resolve_crm.lead', verbose_name='Lead'),
            preserve_default=False,
        ),
    ]
