# Generated by Django 5.0.7 on 2024-10-24 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_projectmaterials'),
        ('resolve_crm', '0008_remove_payment_financier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Prazo para aceitação')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor da proposta')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Token')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aceita'), ('R', 'Recusada')], max_length=1, verbose_name='Status da proposta')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Descrição da proposta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('kits', models.ManyToManyField(to='logistics.solarenergykit', verbose_name='Kits')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.lead', verbose_name='Lead')),
            ],
            options={
                'verbose_name': 'Proposta Comercial',
                'verbose_name_plural': 'Propostas Comerciais',
            },
        ),
    ]
