# Generated by Django 5.0.7 on 2024-09-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_historicaluser_address_remove_user_address_and_more'),
        ('resolve_crm', '0009_remove_historicallead_address_remove_lead_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='first_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='addresses',
            field=models.ManyToManyField(blank=True, null=True, related_name='lead_addresses', to='accounts.address', verbose_name='Endereços'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='first_document',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ'),
        ),
    ]
