# Generated by Django 5.0.7 on 2024-10-28 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0009_comercialproposal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Anexo', 'verbose_name_plural': 'Anexos'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
    ]
