# Generated by Django 5.0.7 on 2024-09-06 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0010_alter_historicallead_first_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-09-06 12:51:29.099311', verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_attachments', to='resolve_crm.lead', verbose_name='Lead'),
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='created_at',
            field=models.DateTimeField(blank=True, default='2024-09-06 12:51:29.09931', editable=False, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='lead',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_attachments', to='resolve_crm.task', verbose_name='Tarefa'),
        ),
    ]
