# Generated by Django 5.0.7 on 2024-10-29 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_documenttype_options_and_more'),
        ('resolve_crm', '0010_alter_attachment_options_alter_lead_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comercialproposal',
            options={'ordering': ['-created_at'], 'verbose_name': 'Proposta Comercial', 'verbose_name_plural': 'Propostas Comerciais'},
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.documentsubtype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='document_subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.documentsubtype', verbose_name='Tipo de Documento'),
        ),
    ]
