# Generated by Django 5.0.7 on 2024-09-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resolve_crm', '0011_attachment_created_at_attachment_lead_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='task',
        ),
        migrations.RemoveField(
            model_name='historicalattachment',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='historicalattachment',
            name='task',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='object_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='content_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='object_id',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
