# Generated by Django 5.0.7 on 2024-10-29 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_documenttype_options_and_more'),
        ('resolve_crm', '0011_alter_comercialproposal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document_subtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.documentsubtype', verbose_name='Subtipo de Documento'),
        ),
        migrations.AlterField(
            model_name='historicalattachment',
            name='document_subtype',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.documentsubtype', verbose_name='Subtipo de Documento'),
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='funnel',
            field=models.CharField(blank=True, choices=[('Q', 'Quente'), ('M', 'Moderado'), ('N', 'Negociação')], max_length=200, null=True, verbose_name='Funil'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='funnel',
            field=models.CharField(blank=True, choices=[('Q', 'Quente'), ('M', 'Moderado'), ('N', 'Negociação')], max_length=200, null=True, verbose_name='Funil'),
        ),
    ]
