# Generated by Django 5.0.7 on 2024-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_historicaluser_address_remove_user_address_and_more'),
        ('resolve_crm', '0012_remove_attachment_lead_remove_attachment_task_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='resolve_crm/attachments/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='addresses',
            field=models.ManyToManyField(related_name='lead_addresses', to='accounts.address', verbose_name='Endereços'),
        ),
    ]
