# Generated by Django 5.0.7 on 2024-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0012_alter_attachment_document_subtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Percentual de Repasse'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='Percentual de Repasse'),
        ),
    ]
