# Generated by Django 5.0.7 on 2024-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0013_alter_attachment_file_alter_lead_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingcampaign',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
