# Generated by Django 5.0.7 on 2024-10-30 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0013_historicalsale_transfer_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deletado')),
            ],
            options={
                'verbose_name': 'Origem',
                'verbose_name_plural': 'Origens',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='historicallead',
            name='origin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.origin', verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.origin', verbose_name='Origem'),
        ),
    ]
