# Generated by Django 5.0.9 on 2024-10-31 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_historicalsolarenergykit_is_default_and_more'),
        ('resolve_crm', '0014_origin_alter_historicallead_origin_alter_lead_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='solar_energy_kit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.solarenergykit', verbose_name='Kit de Energia Solar'),
        ),
        migrations.AddField(
            model_name='project',
            name='solar_energy_kit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.solarenergykit', verbose_name='Kit de Energia Solar'),
            preserve_default=False,
        ),
    ]
