# Generated by Django 5.0.7 on 2024-09-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0014_marketingcampaign_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
