# Generated by Django 5.0.9 on 2024-10-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0015_historicalproject_solar_energy_kit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='kwp',
        ),
        migrations.RemoveField(
            model_name='project',
            name='kwp',
        ),
    ]
