# Generated by Django 5.0.7 on 2024-09-13 15:08

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20240911_1649'),
        ('contracts', '0001_initial'),
        ('engineering', '0001_initial'),
        ('resolve_crm', '0015_historicallead_is_deleted_lead_is_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='document_situation',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='financial_completion_date',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='homologator',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='is_completed_financial',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='project_value',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='document_situation',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='document_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='financial_completion_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='homologator',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_completed_financial',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='project_value',
        ),
        migrations.AddField(
            model_name='attachment',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.documenttype', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='historicalattachment',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Pré-venda'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='', max_length=2, verbose_name='Status da Venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='total_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Pré-venda'),
        ),
        migrations.AddField(
            model_name='sale',
            name='signature_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='', max_length=2, verbose_name='Status da Venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='total_value',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Financier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.address', verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Financiadora',
                'verbose_name_plural': 'Financiadoras',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFinancier',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('address', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.address', verbose_name='Endereço')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Financiadora',
                'verbose_name_plural': 'historical Financiadoras',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalPayment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor')),
                ('payment_type', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno')], max_length=2, verbose_name='Tipo de Pagamento')),
                ('installments_number', models.PositiveSmallIntegerField(verbose_name='Número de Parcelas')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('financier', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.financier', verbose_name='Financiadora')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pagamento',
                'verbose_name_plural': 'historical Pagamentos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('project_number', models.CharField(max_length=20, verbose_name='Número do Projeto')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Projeto Completo')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, verbose_name='Status do Projeto')),
                ('supply_type', models.CharField(choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], max_length=50, verbose_name='Tipo de Fornecimento')),
                ('kwp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kWp')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('designer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Projetista')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('homologator', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Homologador')),
                ('instaled_circuit_breaker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.circuitbreaker', verbose_name='Disjuntor Instalado')),
                ('project_circuit_breaker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.circuitbreaker', verbose_name='Disjuntor do Projeto')),
                ('registered_circuit_breaker', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='engineering.circuitbreaker', verbose_name='Disjuntor Cadastrado')),
                ('sale', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'historical Projeto',
                'verbose_name_plural': 'historical Projetos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor')),
                ('payment_type', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito'), ('B', 'Boleto'), ('F', 'Financiamento'), ('PI', 'Parcelamento interno')], max_length=2, verbose_name='Tipo de Pagamento')),
                ('installments_number', models.PositiveSmallIntegerField(verbose_name='Número de Parcelas')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('financier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.financier', verbose_name='Financiadora')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPaymentInstallment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('installment_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor')),
                ('installment_number', models.PositiveSmallIntegerField(verbose_name='Número da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('paid_at', models.DateTimeField(blank=True, editable=False, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Criado em')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'historical Parcela',
                'verbose_name_plural': 'historical Parcelas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='payment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.payment', verbose_name='Pagamento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.payment', verbose_name='Pagamento'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=20, verbose_name='Valor')),
                ('installment_number', models.PositiveSmallIntegerField(verbose_name='Número da Parcela')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='Pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=20, verbose_name='Número do Projeto')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(verbose_name='Data de Término')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Projeto Completo')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, verbose_name='Status do Projeto')),
                ('supply_type', models.CharField(choices=[('M', 'Monofásico'), ('B', 'Bifásico'), ('T', 'Trifásico')], max_length=50, verbose_name='Tipo de Fornecimento')),
                ('kwp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='kWp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('addresses', models.ManyToManyField(related_name='project_addresses', to='accounts.address', verbose_name='Endereços')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Projetista')),
                ('homologator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homologator_projects', to=settings.AUTH_USER_MODEL, verbose_name='Homologador')),
                ('instaled_circuit_breaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instaled_circuit_breaker', to='engineering.circuitbreaker', verbose_name='Disjuntor Instalado')),
                ('project_circuit_breaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_circuit_breaker', to='engineering.circuitbreaker', verbose_name='Disjuntor do Projeto')),
                ('registered_circuit_breaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_circuit_breaker', to='engineering.circuitbreaker', verbose_name='Disjuntor Cadastrado')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.sale', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
        migrations.DeleteModel(
            name='SaleDocument',
        ),
    ]
