# Generated by Django 5.0.7 on 2024-09-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0016_remove_historicalsale_borrower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='historicalfinancier',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
