# Generated by Django 5.0.4 on 2024-11-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0016_alter_project_options_remove_historicalproject_kwp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsale',
            old_name='is_sale',
            new_name='is_pre_sale',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='is_sale',
            new_name='is_pre_sale',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='designer',
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='contract_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='is_completed_document',
            field=models.BooleanField(default=False, verbose_name='Documento Completo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='contract_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_completed_document',
            field=models.BooleanField(default=False, verbose_name='Documento Completo'),
        ),
    ]
