# Generated by Django 5.0.4 on 2024-11-08 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0017_rename_is_sale_historicalsale_is_pre_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltask',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Tarefa do Lead', 'verbose_name_plural': 'historical Tarefas do Lead'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Tarefa do Lead', 'verbose_name_plural': 'Tarefas do Lead'},
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='supply_type',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='is_completed_document',
        ),
        migrations.RemoveField(
            model_name='historicalsale',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='project',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='project',
            name='supply_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='is_completed_document',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lead',
        ),
        migrations.AddField(
            model_name='contractsubmission',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em'),
        ),
        migrations.AddField(
            model_name='contractsubmission',
            name='key_number',
            field=models.CharField(default=12314, max_length=20, verbose_name='Número da Chave'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractsubmission',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resolve_crm.sale', verbose_name='Venda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='designer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Projetista'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='designer_conclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Projeto'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='financial_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Financeiro'),
        ),
        migrations.AddField(
            model_name='origin',
            name='type',
            field=models.CharField(choices=[('IB', 'Inbound'), ('OB', 'Outbound')], default='IB', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Projetista'),
        ),
        migrations.AddField(
            model_name='project',
            name='designer_conclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Projeto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='financial_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Financeiro'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('CO', 'Concluído'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, null=True, verbose_name='Status do Projeto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('CO', 'Concluído'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, null=True, verbose_name='Status do Projeto'),
        ),
    ]
