# Generated by Django 5.0.7 on 2024-09-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0017_financier_is_deleted_historicalfinancier_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deletado'),
        ),
    ]
