# Generated by Django 5.0.7 on 2024-09-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0018_historicaltask_is_deleted_task_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='payment',
        ),
        migrations.AddField(
            model_name='historicalpayment',
            name='sale',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='resolve_crm.sale', verbose_name='Venda'),
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='resolve_crm.sale', verbose_name='Venda'),
            preserve_default=False,
        ),
    ]
