# Generated by Django 5.0.4 on 2024-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0018_alter_historicaltask_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='total_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_value',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20, verbose_name='Valor'),
        ),
    ]
