# Generated by Django 5.0.4 on 2024-11-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0019_alter_historicalsale_total_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='project_circuit_breaker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_circuit_breaker',
        ),
    ]
