# Generated by Django 5.0.4 on 2024-11-08 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0008_resquesttype_situationenergycompany_supplyadequance_and_more'),
        ('resolve_crm', '0021_remove_historicalproject_instaled_circuit_breaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registered_circuit_breaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_circuit_breaker2', to='engineering.circuitbreaker', verbose_name='Disjuntor Cadastrado'),
        ),
    ]
