# Generated by Django 5.0.4 on 2024-11-08 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_historicalmaterials_type_and_more'),
        ('resolve_crm', '0022_alter_project_registered_circuit_breaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='registered_circuit_breaker',
        ),
        migrations.RemoveField(
            model_name='project',
            name='registered_circuit_breaker',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='registered_circuit_breaker2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.materials', verbose_name='Disjuntor Cadastrado'),
        ),
        migrations.AddField(
            model_name='project',
            name='registered_circuit_breaker2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_circuit_breaker2', to='logistics.materials', verbose_name='Disjuntor Cadastrado'),
        ),
    ]
