# Generated by Django 5.0.4 on 2024-11-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_remove_historicalmaterials_type_and_more'),
        ('resolve_crm', '0023_remove_historicalproject_registered_circuit_breaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='registered_circuit_breaker2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_circuit_breaker', to='logistics.materials', verbose_name='Disjuntor Cadastrado'),
        ),
    ]
