# Generated by Django 5.0.4 on 2024-11-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_rename_historicalsolarenergykit_historicalproduct_and_more'),
        ('resolve_crm', '0024_alter_project_registered_circuit_breaker2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='registered_circuit_breaker2',
            new_name='registered_circuit_breaker',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='registered_circuit_breaker2',
            new_name='registered_circuit_breaker',
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='solar_energy_kit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.saleproduct', verbose_name='Kit de Energia Solar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='solar_energy_kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.saleproduct', verbose_name='Kit de Energia Solar'),
        ),
    ]
