# Generated by Django 5.0.4 on 2024-11-09 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_alter_historicalproduct_options_and_more'),
        ('resolve_crm', '0025_rename_registered_circuit_breaker2_historicalproject_registered_circuit_breaker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comercialproposal',
            name='kits',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='solar_energy_kit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='solar_energy_kit',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.saleproduct', verbose_name='product de Energia Solar'),
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='logistics.saleproduct', verbose_name='product de Energia Solar'),
            preserve_default=False,
        ),
    ]
