# Generated by Django 5.0.4 on 2024-11-12 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_remove_historicalproduct_price_remove_product_price'),
        ('resolve_crm', '0026_remove_comercialproposal_kits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logistics.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Produto'),
        ),
    ]
