# Generated by Django 5.0.4 on 2024-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0027_alter_historicalproject_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='kwp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Potência (kWp)'),
        ),
        migrations.AddField(
            model_name='lead',
            name='kwp',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, verbose_name='Potência (kWp)'),
        ),
    ]
