# Generated by Django 5.0.4 on 2024-11-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0028_historicallead_kwp_lead_kwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='qualification',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qualificação'),
        ),
        migrations.AddField(
            model_name='lead',
            name='qualification',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qualificação'),
        ),
    ]
