# Generated by Django 5.0.4 on 2024-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_alter_projectmaterials_amount_and_more'),
        ('resolve_crm', '0029_historicallead_qualification_lead_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.ManyToManyField(related_name='projects', through='logistics.ProjectMaterials', to='logistics.materials'),
        ),
    ]
