# Generated by Django 5.0.4 on 2024-11-13 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0030_project_materials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallead',
            name='funnel',
            field=models.CharField(blank=True, choices=[('N', 'Não Interessado'), ('P', 'Pouco Interessado'), ('I', 'Interessado'), ('M', 'Muito Interessado'), ('PC', 'Pronto para Comprar')], max_length=200, null=True, verbose_name='Funil'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='funnel',
            field=models.CharField(blank=True, choices=[('N', 'Não Interessado'), ('P', 'Pouco Interessado'), ('I', 'Interessado'), ('M', 'Muito Interessado'), ('PC', 'Pronto para Comprar')], max_length=200, null=True, verbose_name='Funil'),
        ),
    ]
