# Generated by Django 5.0.4 on 2024-11-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0031_alter_historicallead_funnel_alter_lead_funnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallead',
            name='moved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Movido em'),
        ),
        migrations.AddField(
            model_name='lead',
            name='moved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Movido em'),
        ),
    ]
