# Generated by Django 5.0.4 on 2024-11-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0032_historicallead_moved_at_lead_moved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='document_completion_date',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='document_completion_date',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='document_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Documento'),
        ),
        migrations.AddField(
            model_name='project',
            name='document_completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Documento'),
        ),
    ]
