# Generated by Django 5.0.4 on 2024-11-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_saleproduct_commercial_proposal_and_more'),
        ('resolve_crm', '0033_remove_historicalsale_document_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comercialproposal',
            name='products',
            field=models.ManyToManyField(through='logistics.SaleProduct', to='logistics.product', verbose_name='Produtos'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(through='logistics.SaleProduct', to='logistics.product', verbose_name='Produtos'),
        ),
    ]
