# Generated by Django 5.0.4 on 2024-11-18 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_alter_saleproduct_commercial_proposal_and_more'),
        ('resolve_crm', '0034_comercialproposal_products_sale_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='contractsubmission',
            options={'ordering': ['-submit_datetime'], 'verbose_name': 'Envio de Contrato', 'verbose_name_plural': 'Envios de Contrato'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tarefa do Lead', 'verbose_name_plural': 'Tarefas do Lead'},
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logistics.product', verbose_name='Produto'),
        ),
    ]
