# Generated by Django 5.0.4 on 2024-11-18 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0035_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='resolve_crm.sale', verbose_name='Venda'),
        ),
    ]
