# Generated by Django 5.0.4 on 2024-11-18 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0036_alter_project_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercialproposal',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='resolve_crm.lead', verbose_name='Lead'),
        ),
    ]
