# Generated by Django 5.0.4 on 2024-11-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0037_alter_comercialproposal_lead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalattachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='historicalattachment',
            name='document_subtype',
        ),
        migrations.RemoveField(
            model_name='historicalattachment',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='historicalattachment',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='HistoricalAttachment',
        ),
    ]
