# Generated by Django 5.0.4 on 2024-11-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0038_remove_historicalattachment_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsubmission',
            name='key_number',
            field=models.CharField(max_length=50, verbose_name='Número da Chave'),
        ),
    ]
