# Generated by Django 5.0.4 on 2024-11-25 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0039_alter_contractsubmission_key_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='transfer_percentage',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentagem de Repasse'),
        ),
    ]
