# Generated by Django 5.0.4 on 2024-11-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0040_alter_historicalsale_transfer_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsubmission',
            name='request_signature_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave de solicitação de assinatura'),
        ),
        migrations.AlterField(
            model_name='contractsubmission',
            name='key_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Chave'),
        ),
    ]
