# Generated by Django 5.0.4 on 2024-11-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0041_contractsubmission_request_signature_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='document_completion_date',
            new_name='documention_completion_date',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='document_completion_date',
            new_name='documention_completion_date',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='is_documentation_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documentos Completos'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_documentation_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Documentos Completos'),
        ),
    ]
