# Generated by Django 5.0.4 on 2024-11-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0042_rename_document_completion_date_historicalproject_documention_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='designer_status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('CO', 'Concluído'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, null=True, verbose_name='Status do Projeto de Engenharia'),
        ),
        migrations.AddField(
            model_name='project',
            name='designer_status',
            field=models.CharField(blank=True, choices=[('P', 'Pendente'), ('CO', 'Concluído'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], max_length=2, null=True, verbose_name='Status do Projeto de Engenharia'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='designer_conclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Projeto de Engenharia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer_conclusion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão do Projeto de Engenharia'),
        ),
    ]
