# Generated by Django 5.0.4 on 2024-11-27 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0043_historicalproject_designer_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Etapa')),
                ('slug', models.SlugField(max_length=100, verbose_name='Slug')),
                ('default_duration_days', models.PositiveIntegerField(default=0, verbose_name='Prazo Padrão (em dias)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição da Etapa')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_steps', to='resolve_crm.project')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_steps', to='resolve_crm.step')),
            ],
            options={
                'verbose_name': 'Etapa do Projeto',
                'verbose_name_plural': 'Etapas dos Projetos',
                'unique_together': {('project', 'step')},
            },
        ),
    ]
