# Generated by Django 5.0.4 on 2024-12-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0045_step_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsubmission',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_submissions', to='resolve_crm.sale', verbose_name='Venda'),
        ),
    ]
