# Generated by Django 5.0.4 on 2024-12-03 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0046_alter_contractsubmission_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='id_plant',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID da Planta'),
        ),
        migrations.AddField(
            model_name='project',
            name='id_plant',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID da Planta'),
        ),
    ]
