# Generated by Django 5.0.4 on 2024-12-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0047_historicalproject_id_plant_project_id_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='id_plant',
        ),
        migrations.RemoveField(
            model_name='project',
            name='id_plant',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='plant_integration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID da Usina'),
        ),
        migrations.AddField(
            model_name='project',
            name='plant_integration',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID da Usina'),
        ),
    ]
