# Generated by Django 5.0.4 on 2024-12-17 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0039_schedule_products'),
        ('resolve_crm', '0048_remove_historicalproject_id_plant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='inspection',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='field_services.schedule', verbose_name='Agendamento da Vistoria'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('PG', 'Pago'), ('PA', 'Parcialmente Pago'), ('D', 'Distrato')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='project',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_field_services', to='field_services.schedule', verbose_name='Agendamento da Vistoria'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('PG', 'Pago'), ('PA', 'Parcialmente Pago'), ('D', 'Distrato')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
    ]
