# Generated by Django 5.0.4 on 2024-12-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0049_historicalproject_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='financial_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído')], default='P', max_length=2, verbose_name='Status do Financeiro'),
        ),
        migrations.AddField(
            model_name='sale',
            name='financial_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído')], default='P', max_length=2, verbose_name='Status do Financeiro'),
        ),
    ]
