# Generated by Django 5.0.4 on 2024-12-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0050_historicalsale_financial_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='financial_status',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='financial_status',
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
    ]
