# Generated by Django 5.0.4 on 2025-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0052_alter_historicalproject_status_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstep',
            name='nps',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='NPS'),
        ),
    ]
