# Generated by Django 5.0.4 on 2025-01-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_branch_discount_allowed_and_more'),
        ('resolve_crm', '0053_projectstep_nps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('person_type', models.CharField(choices=[('F', 'Física'), ('J', 'Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('branches', models.ManyToManyField(related_name='contract_templates', to='accounts.branch', verbose_name='Unidades')),
            ],
            options={
                'verbose_name': 'Modelo de Contrato',
                'verbose_name_plural': 'Modelos de Contrato',
                'ordering': ['name'],
            },
        ),
    ]
