# Generated by Django 5.0.4 on 2025-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0054_contracttemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingcampaign',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='resolve_crm/img/marketing_campaign/', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='marketingcampaign',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
    ]
