# Generated by Django 5.0.4 on 2025-01-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0056_historicalsale_supplier_sale_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='is_completed_financial',
            field=models.BooleanField(default=False, verbose_name='Financeiro Completo'),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_completed_financial',
            field=models.BooleanField(default=False, verbose_name='Financeiro Completo'),
        ),
    ]
