# Generated by Django 5.0.4 on 2025-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0057_historicalsale_is_completed_financial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsubmission',
            name='envelope_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave do Envelope'),
        ),
        migrations.AlterField(
            model_name='contractsubmission',
            name='key_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave do Documento'),
        ),
        migrations.AlterField(
            model_name='contractsubmission',
            name='request_signature_key',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave do Signatário'),
        ),
    ]
