# Generated by Django 5.0.4 on 2025-01-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0058_contractsubmission_envelope_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='contract_number',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=20, null=True, verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='contract_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Número do Contrato'),
        ),
    ]
