# Generated by Django 5.0.4 on 2025-01-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0059_alter_historicalsale_contract_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído'), ('CA', 'Cancelado')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído'), ('CA', 'Cancelado')], default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
    ]
