# Generated by Django 5.0.4 on 2025-01-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0060_alter_historicalsale_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='billing_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1, null=True, verbose_name='Mês de Faturamento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], default=1, null=True, verbose_name='Mês de Faturamento'),
        ),
    ]
