# Generated by Django 5.0.4 on 2025-01-31 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0061_historicalsale_billing_month_sale_billing_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_billing_month', 'Can change billing month')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
