# Generated by Django 5.0.4 on 2025-01-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0062_alter_sale_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='billing_month',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='billing_month',
        ),
    ]
