# Generated by Django 5.0.4 on 2025-01-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0063_remove_historicalsale_billing_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mês de Faturamento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Mês de Faturamento'),
        ),
    ]
