# Generated by Django 5.0.4 on 2025-01-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0064_historicalsale_billing_date_sale_billing_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_billing_date', 'Can change billing month')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de competência'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de competência'),
        ),
    ]
