# Generated by Django 5.0.4 on 2025-01-31 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0065_alter_sale_options_alter_historicalsale_billing_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_billing_date', 'Can change billing date')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
