# Generated by Django 5.0.4 on 2025-02-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0067_alter_historicalproject_designer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='designer_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('CO', 'Concluído'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='P', max_length=2, verbose_name='Status do Projeto de Engenharia'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('CO', 'Concluído'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], default='P', max_length=2, verbose_name='Status do Projeto de Engenharia'),
        ),
    ]
