# Generated by Django 5.0.4 on 2025-02-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0068_alter_historicalproject_designer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='material_list_is_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lista de Materiais Finalizada'),
        ),
        migrations.AddField(
            model_name='project',
            name='material_list_is_completed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Lista de Materiais Finalizada'),
        ),
    ]
