# Generated by Django 5.0.4 on 2025-02-13 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0069_historicalproject_material_list_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_unready_project', 'Can change unready project')], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
