# Generated by Django 5.0.4 on 2025-02-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field_services', '0066_historicalschedule_branch_schedule_branch'),
        ('resolve_crm', '0070_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='inspections',
            field=models.ManyToManyField(blank=True, related_name='lead_inspections', to='field_services.schedule', verbose_name='Vistorias'),
        ),
    ]
