# Generated by Django 5.0.4 on 2025-03-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0071_lead_inspections'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
