# Generated by Django 5.0.4 on 2025-03-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0072_historicalsale_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='inspections',
        ),
    ]
