# Generated by Django 5.0.4 on 2025-03-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0074_reason_historicalreason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsale',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cancellation_reason',
        ),
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.ManyToManyField(blank=True, related_name='cancellation_reason_sales', to='resolve_crm.reason', verbose_name='Motivo do Cancelamento'),
        ),
    ]
