# Generated by Django 5.0.4 on 2025-03-03 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0075_remove_historicalsale_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='cancellation_reason',
            new_name='cancellation_reasons',
        ),
    ]
