# Generated by Django 5.0.4 on 2025-03-06 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_branch_energy_company_and_more'),
        ('core', '0036_alter_tag_options'),
        ('field_services', '0070_schedule_leads'),
        ('logistics', '0026_projectmaterials_material_class'),
        ('resolve_crm', '0076_rename_cancellation_reason_sale_cancellation_reasons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comercialproposal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='comercialproposal',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='resolve_crm.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='core.column', verbose_name='Coluna'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_leads', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resolve_crm.origin', verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='sdr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_sdr', to=settings.AUTH_USER_MODEL, verbose_name='SDR'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_seller', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='designer_projects', to=settings.AUTH_USER_MODEL, verbose_name='Projetista'),
        ),
        migrations.AlterField(
            model_name='project',
            name='homologator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='homologator_projects', to=settings.AUTH_USER_MODEL, verbose_name='Homologador'),
        ),
        migrations.AlterField(
            model_name='project',
            name='inspection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_field_services', to='field_services.schedule', verbose_name='Agendamento da Vistoria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistics.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='registered_circuit_breaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_circuit_breaker', to='logistics.materials', verbose_name='Disjuntor Cadastrado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='resolve_crm.sale', verbose_name='Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.branch', verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_sales', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='resolve_crm.marketingcampaign', verbose_name='Campanha de Marketing'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manager_sales', to=settings.AUTH_USER_MODEL, verbose_name='Gerente de Vendas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sales_supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_sales', to=settings.AUTH_USER_MODEL, verbose_name='Supervisor de Vendas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_sales', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_sales', to=settings.AUTH_USER_MODEL, verbose_name='Fornecedor'),
        ),
    ]
