# Generated by Django 5.0.4 on 2025-03-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0077_alter_comercialproposal_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='signature_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='signature_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Data da Assinatura'),
        ),
    ]
