# Generated by Django 5.0.4 on 2025-03-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0078_alter_historicalsale_signature_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='reference_table',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabela de Referência'),
        ),
        migrations.AddField(
            model_name='sale',
            name='reference_table',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabela de Referência'),
        ),
    ]
