# Generated by Django 4.2.9 on 2025-03-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0079_historicalsale_reference_table_sale_reference_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='billing_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de competência'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='created_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='financial_completion_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Conclusão do Financeiro'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='is_completed_financial',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Financeiro Completo'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='is_pre_sale',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Pré-venda'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído'), ('CA', 'Cancelado')], db_index=True, default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='signature_date',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], db_index=True, default='P', max_length=2, verbose_name='Status da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='billing_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de competência'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='financial_completion_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data de Conclusão do Financeiro'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_completed_financial',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Financeiro Completo'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='is_pre_sale',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Pré-venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('L', 'Liberado'), ('C', 'Concluído'), ('CA', 'Cancelado')], db_index=True, default='P', max_length=2, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='signature_date',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato')], db_index=True, default='P', max_length=2, verbose_name='Status da Venda'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['payment_status'], name='resolve_crm_payment_6be18d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['status'], name='resolve_crm_status_85bd3b_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['billing_date'], name='resolve_crm_billing_7af33a_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['created_at'], name='resolve_crm_created_6a6f46_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch'], name='resolve_crm_branch__87b7c9_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_pre_sale'], name='resolve_crm_is_pre__c9130f_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_completed_financial'], name='resolve_crm_is_comp_adba90_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['financial_completion_date'], name='resolve_crm_financi_c76ecf_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['contract_number'], name='resolve_crm_contrac_9a9b28_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['branch', 'payment_status'], name='resolve_crm_branch__a16f18_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['is_pre_sale', 'payment_status'], name='resolve_crm_is_pre__eaf747_idx'),
        ),
    ]
