# Generated by Django 5.0.4 on 2025-03-15 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_user_addresses'),
        ('logistics', '0026_projectmaterials_material_class'),
        ('resolve_crm', '0079_historicalsale_reference_table_sale_reference_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pre_sale', True)), fields=('customer',), name='unique_pre_sale_per_customer'),
        ),
    ]
