# Generated by Django 4.2.9 on 2025-03-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0080_alter_historicalsale_billing_date_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['project_number'], name='resolve_crm_project_d68590_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='resolve_crm_status_814ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['designer_status'], name='resolve_crm_designe_2f8437_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['start_date'], name='resolve_crm_start_d_972cca_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['end_date'], name='resolve_crm_end_dat_efb280_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_completed'], name='resolve_crm_is_comp_c959b7_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_documentation_completed'], name='resolve_crm_is_docu_578e38_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['material_list_is_completed'], name='resolve_crm_materia_66cb53_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['documention_completion_date'], name='resolve_crm_documen_9adaca_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='resolve_crm_created_d18057_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sale'], name='resolve_crm_sale_id_dd93bd_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sale', 'status'], name='resolve_crm_sale_id_a9b9ab_idx'),
        ),
    ]
