# Generated by Django 4.2.9 on 2025-03-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0080_sale_unique_pre_sale_per_customer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='unique_pre_sale_per_customer',
        ),
    ]
