# Generated by Django 4.2.9 on 2025-03-27 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0081_project_resolve_crm_project_d68590_idx_and_more'),
        ('resolve_crm', '0081_remove_sale_unique_pre_sale_per_customer'),
    ]

    operations = [
    ]
