# Generated by Django 4.2.9 on 2025-04-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0082_merge_20250327_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_billing_date', 'Can change billing date'), ('can_change_fineshed_sale', 'Can change finished sale')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
