# Generated by Django 4.2.9 on 2025-04-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0083_alter_sale_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='signature_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data da Assinatura'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='signature_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Data da Assinatura'),
        ),
    ]
