# Generated by Django 4.2.9 on 2025-05-08 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0084_alter_historicalsale_signature_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_unready_project', 'Can change unready project'), ('can_view_journey', 'Can view journey')], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
