# Generated by Django 4.2.9 on 2025-05-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0085_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_unready_project', 'Can change unready project'), ('can_view_journey', 'Can view journey'), ('can_manage_journey', 'Can manage journey')], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
    ]
