# Generated by Django 4.2.9 on 2025-05-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0086_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('D', 'Entrega Direta'), ('C', 'Entrega CD')], max_length=1, null=True, verbose_name='Tipo de Entrega'),
        ),
        migrations.AddField(
            model_name='project',
            name='delivery_type',
            field=models.CharField(blank=True, choices=[('D', 'Entrega Direta'), ('C', 'Entrega CD')], max_length=1, null=True, verbose_name='Tipo de Entrega'),
        ),
    ]
