# Generated by Django 4.2.9 on 2025-05-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0087_historicalproject_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato'), ('ED', 'Em Distrato')], db_index=True, default='P', max_length=2, verbose_name='Status da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('F', 'Finalizado'), ('EA', 'Em Andamento'), ('C', 'Cancelado'), ('D', 'Distrato'), ('ED', 'Em Distrato')], db_index=True, default='P', max_length=2, verbose_name='Status da Venda'),
        ),
    ]
