# Generated by Django 4.2.9 on 2025-06-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0089_reward_historicalsale_reward_sale_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='monitoring_app_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=1, verbose_name='Status do App de Monitoramento'),
        ),
        migrations.AddField(
            model_name='project',
            name='monitoring_app_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('C', 'Concluído')], default='P', max_length=1, verbose_name='Status do App de Monitoramento'),
        ),
    ]
