# Generated by Django 4.2.9 on 2025-06-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0090_historicalproject_monitoring_app_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='monitoring_app_status',
            field=models.CharField(choices=[('C', 'Criado'), ('E', 'Criado e Entregue'), ('S', 'Cliente sem Internet'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status do App de Monitoramento'),
        ),
        migrations.AlterField(
            model_name='project',
            name='monitoring_app_status',
            field=models.CharField(choices=[('C', 'Criado'), ('E', 'Criado e Entregue'), ('S', 'Cliente sem Internet'), ('P', 'Pendente')], default='P', max_length=1, verbose_name='Status do App de Monitoramento'),
        ),
    ]
