# Generated by Django 4.2.9 on 2025-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0091_alter_historicalproject_monitoring_app_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsale',
            name='financier_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Financeiro'),
        ),
        migrations.AddField(
            model_name='historicalsale',
            name='financier_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do Financeiro'),
        ),
        migrations.AddField(
            model_name='sale',
            name='financier_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Financeiro'),
        ),
        migrations.AddField(
            model_name='sale',
            name='financier_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, verbose_name='ID do Financeiro'),
        ),
    ]
