# Generated by Django 4.2.9 on 2025-07-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0092_historicalsale_financier_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='datalogger_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Datalogger'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='inverter_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Inversor'),
        ),
        migrations.AddField(
            model_name='project',
            name='datalogger_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Datalogger'),
        ),
        migrations.AddField(
            model_name='project',
            name='inverter_serial_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Série do Inversor'),
        ),
    ]
