# Generated by Django 4.2.9 on 2025-07-23 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0093_historicalproject_datalogger_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='datalogger_serial_number',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='inverter_serial_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='datalogger_serial_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='inverter_serial_number',
        ),
    ]
