# Generated by Django 4.2.9 on 2025-08-06 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0094_remove_historicalproject_datalogger_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-created_at'], 'permissions': [('can_change_billing_date', 'Can change billing date'), ('can_change_fineshed_sale', 'Can change finished sale'), ('view_dashboard', 'Pode ver dashboard no sistema de vendas'), ('view_ranking', 'Pode ver ranking de vendas')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
