# Generated by Django 4.2.9 on 2025-09-09 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resolve_crm', '0095_alter_sale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='financier_monitoring_status',
            field=models.CharField(choices=[('SFI', 'Sem Foto da Instalação'), ('CMK', 'Confirmar Mensagem de Kit Entregue'), ('FTA', 'Falha na Transferência (Em Análise)'), ('AAD', 'Aguardando Aprovação da Documentação de Equipamento Entregue'), ('F', 'Finalizado')], default='P', max_length=3, verbose_name='Status do Monitoramento do Financeiro'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='financier_monitoring_status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Alteração do Status'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='financier_monitoring_status_changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
        migrations.AddField(
            model_name='project',
            name='financier_monitoring_status',
            field=models.CharField(choices=[('SFI', 'Sem Foto da Instalação'), ('CMK', 'Confirmar Mensagem de Kit Entregue'), ('FTA', 'Falha na Transferência (Em Análise)'), ('AAD', 'Aguardando Aprovação da Documentação de Equipamento Entregue'), ('F', 'Finalizado')], default='P', max_length=3, verbose_name='Status do Monitoramento do Financeiro'),
        ),
        migrations.AddField(
            model_name='project',
            name='financier_monitoring_status_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Alteração do Status'),
        ),
        migrations.AddField(
            model_name='project',
            name='financier_monitoring_status_changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financier_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por'),
        ),
    ]
