# Generated by Django 4.2.9 on 2025-09-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0096_historicalproject_financier_monitoring_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='financier_monitoring_status',
            field=models.CharField(blank=True, choices=[('SFI', 'Sem Foto da Instalação'), ('CMK', 'Confirmar Mensagem de Kit Entregue'), ('FTA', 'Falha na Transferência (Em Análise)'), ('AAD', 'Aguardando Aprovação da Documentação de Equipamento Entregue'), ('F', 'Finalizado')], max_length=3, null=True, verbose_name='Status do Monitoramento do Financeiro'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financier_monitoring_status',
            field=models.CharField(blank=True, choices=[('SFI', 'Sem Foto da Instalação'), ('CMK', 'Confirmar Mensagem de Kit Entregue'), ('FTA', 'Falha na Transferência (Em Análise)'), ('AAD', 'Aguardando Aprovação da Documentação de Equipamento Entregue'), ('F', 'Finalizado')], max_length=3, null=True, verbose_name='Status do Monitoramento do Financeiro'),
        ),
    ]
