# Generated by Django 4.2.9 on 2025-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resolve_crm', '0098_alter_historicalproject_financier_monitoring_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='financier_monitoring_status',
            field=models.CharField(blank=True, choices=[('SFI', 'Sem Foto da Instalação'), ('CMK', 'Confirmar Mensagem de Kit Entregue'), ('FTA', 'Falha na Transferência (Em Análise)'), ('AAD', 'Aguardando Aprovação da Documentação de Equipamento Entregue'), ('PPD', 'Pend. Preenchimento de Dados de Monitoramento'), ('ACM', 'Aguardando Confirmação de Monitoração'), ('PC', 'Projeto Cancelado'), ('ADE', 'Aguardando Documentação de Equipamento Entregue'), ('EEA', 'Equipamento Entregue (Aguardando Próxima Etapa)'), ('F', 'Finalizado'), ('PCG', 'PEND. CLIENTE CONFIRMAR MENSAGEM DE GERAÇÃO'), ('PVI', 'Pend. validar instalação com inversor'), ('SGI', 'Não foi identificada geração de energia no(s) inversor(es)'), ('EPI', 'ERRO NA POTENCIA DO INVERSOR'), ('IVD', 'INSTALAÇÃO VALIDADA'), ('PG', 'Pago')], max_length=3, null=True, verbose_name='Status do Monitoramento do Financeiro'),
        ),
        migrations.AlterField(
            model_name='project',
            name='financier_monitoring_status',
            field=models.CharField(blank=True, choices=[('SFI', 'Sem Foto da Instalação'), ('CMK', 'Confirmar Mensagem de Kit Entregue'), ('FTA', 'Falha na Transferência (Em Análise)'), ('AAD', 'Aguardando Aprovação da Documentação de Equipamento Entregue'), ('PPD', 'Pend. Preenchimento de Dados de Monitoramento'), ('ACM', 'Aguardando Confirmação de Monitoração'), ('PC', 'Projeto Cancelado'), ('ADE', 'Aguardando Documentação de Equipamento Entregue'), ('EEA', 'Equipamento Entregue (Aguardando Próxima Etapa)'), ('F', 'Finalizado'), ('PCG', 'PEND. CLIENTE CONFIRMAR MENSAGEM DE GERAÇÃO'), ('PVI', 'Pend. validar instalação com inversor'), ('SGI', 'Não foi identificada geração de energia no(s) inversor(es)'), ('EPI', 'ERRO NA POTENCIA DO INVERSOR'), ('IVD', 'INSTALAÇÃO VALIDADA'), ('PG', 'Pago')], max_length=3, null=True, verbose_name='Status do Monitoramento do Financeiro'),
        ),
    ]
